/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingRemoveAccountingAccount } from "../../funcs/accountingRemoveAccountingAccount.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RemoveAccountingAccountRequest$inboundSchema,
};

export const tool$accountingRemoveAccountingAccount: ToolDefinition<
  typeof args
> = {
  name: "accounting-remove-accounting-account",
  description: `Remove an account`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accountingRemoveAccountingAccount(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
