/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingGetAccountingCategory } from "../../funcs/accountingGetAccountingCategory.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAccountingCategoryRequest$inboundSchema,
};

export const tool$accountingGetAccountingCategory: ToolDefinition<typeof args> =
  {
    name: "accounting-get-accounting-category",
    description: `Retrieve a category`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await accountingGetAccountingCategory(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
