/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingListAccountingCreditmemoes } from "../../funcs/accountingListAccountingCreditmemoes.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListAccountingCreditmemoesRequest$inboundSchema,
};

export const tool$accountingListAccountingCreditmemoes: ToolDefinition<
  typeof args
> = {
  name: "accounting-list-accounting-creditmemoes",
  description: `List all creditmemoes`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accountingListAccountingCreditmemoes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
