/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingListAccountingReports } from "../../funcs/accountingListAccountingReports.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListAccountingReportsRequest$inboundSchema,
};

export const tool$accountingListAccountingReports: ToolDefinition<typeof args> =
  {
    name: "accounting-list-accounting-reports",
    description: `List all reports`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await accountingListAccountingReports(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
