/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { candidateUpdateAtsCandidate } from "../../funcs/candidateUpdateAtsCandidate.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateAtsCandidateRequest$inboundSchema,
};

export const tool$candidateUpdateAtsCandidate: ToolDefinition<typeof args> = {
  name: "candidate-update-ats-candidate",
  description: `Update a candidate`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await candidateUpdateAtsCandidate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
