/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { commerceCreateCommerceItem } from "../../funcs/commerceCreateCommerceItem.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCommerceItemRequest$inboundSchema,
};

export const tool$commerceCreateCommerceItem: ToolDefinition<typeof args> = {
  name: "commerce-create-commerce-item",
  description: `Create an item`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await commerceCreateCommerceItem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
