/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmPatchCrmContact } from "../../funcs/crmPatchCrmContact.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PatchCrmContactRequest$inboundSchema,
};

export const tool$crmPatchCrmContact: ToolDefinition<typeof args> = {
  name: "crm-patch-crm-contact",
  description: `Update a contact`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await crmPatchCrmContact(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
