/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmRemoveCrmEvent } from "../../funcs/crmRemoveCrmEvent.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RemoveCrmEventRequest$inboundSchema,
};

export const tool$crmRemoveCrmEvent: ToolDefinition<typeof args> = {
  name: "crm-remove-crm-event",
  description: `Remove an event`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await crmRemoveCrmEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
