/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { hrisListHrisGroups } from "../../funcs/hrisListHrisGroups.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListHrisGroupsRequest$inboundSchema,
};

export const tool$hrisListHrisGroups: ToolDefinition<typeof args> = {
  name: "hris-list-hris-groups",
  description: `List all groups`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await hrisListHrisGroups(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
