/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { hrisPatchHrisEmployee } from "../../funcs/hrisPatchHrisEmployee.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PatchHrisEmployeeRequest$inboundSchema,
};

export const tool$hrisPatchHrisEmployee: ToolDefinition<typeof args> = {
  name: "hris-patch-hris-employee",
  description: `Update an employee`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await hrisPatchHrisEmployee(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
