/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { instructorRemoveLmsInstructor } from "../../funcs/instructorRemoveLmsInstructor.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RemoveLmsInstructorRequest$inboundSchema,
};

export const tool$instructorRemoveLmsInstructor: ToolDefinition<typeof args> = {
  name: "instructor-remove-lms-instructor",
  description: `Remove an instructor`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await instructorRemoveLmsInstructor(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
