/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { orderRemoveAccountingOrder } from "../../funcs/orderRemoveAccountingOrder.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RemoveAccountingOrderRequest$inboundSchema,
};

export const tool$orderRemoveAccountingOrder: ToolDefinition<typeof args> = {
  name: "order-remove-accounting-order",
  description: `Remove an order`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await orderRemoveAccountingOrder(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
