/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { payslipListHrisPayslips } from "../../funcs/payslipListHrisPayslips.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListHrisPayslipsRequest$inboundSchema,
};

export const tool$payslipListHrisPayslips: ToolDefinition<typeof args> = {
  name: "payslip-list-hris-payslips",
  description: `List all payslips`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await payslipListHrisPayslips(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
