/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectRemoveTaskProject } from "../../funcs/projectRemoveTaskProject.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RemoveTaskProjectRequest$inboundSchema,
};

export const tool$projectRemoveTaskProject: ToolDefinition<typeof args> = {
  name: "project-remove-task-project",
  description: `Remove a project`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await projectRemoveTaskProject(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
