/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionCreatePaymentSubscription } from "../../funcs/subscriptionCreatePaymentSubscription.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreatePaymentSubscriptionRequest$inboundSchema,
};

export const tool$subscriptionCreatePaymentSubscription: ToolDefinition<
  typeof args
> = {
  name: "subscription-create-payment-subscription",
  description: `Create a subscription`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscriptionCreatePaymentSubscription(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
