/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ticketingGetTicketingNote } from "../../funcs/ticketingGetTicketingNote.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTicketingNoteRequest$inboundSchema,
};

export const tool$ticketingGetTicketingNote: ToolDefinition<typeof args> = {
  name: "ticketing-get-ticketing-note",
  description: `Retrieve a note`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ticketingGetTicketingNote(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
