/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { unifiedRemoveUnifiedWebhook } from "../../funcs/unifiedRemoveUnifiedWebhook.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RemoveUnifiedWebhookRequest$inboundSchema,
};

export const tool$unifiedRemoveUnifiedWebhook: ToolDefinition<typeof args> = {
  name: "unified-remove-unified-webhook",
  description: `Remove webhook subscription`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await unifiedRemoveUnifiedWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
