/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccountingLineitem,
  AccountingLineitem$inboundSchema,
  AccountingLineitem$Outbound,
  AccountingLineitem$outboundSchema,
} from "./accountinglineitem.js";
import {
  PropertyAccountingSalesorderBillingAddress,
  PropertyAccountingSalesorderBillingAddress$inboundSchema,
  PropertyAccountingSalesorderBillingAddress$Outbound,
  PropertyAccountingSalesorderBillingAddress$outboundSchema,
} from "./propertyaccountingsalesorderbillingaddress.js";
import {
  PropertyAccountingSalesorderShippingAddress,
  PropertyAccountingSalesorderShippingAddress$inboundSchema,
  PropertyAccountingSalesorderShippingAddress$Outbound,
  PropertyAccountingSalesorderShippingAddress$outboundSchema,
} from "./propertyaccountingsalesordershippingaddress.js";

export const AccountingSalesorderStatus = {
  Draft: "DRAFT",
  Voided: "VOIDED",
  Authorized: "AUTHORIZED",
  Paid: "PAID",
  PartiallyPaid: "PARTIALLY_PAID",
  PartiallyRefunded: "PARTIALLY_REFUNDED",
  Refunded: "REFUNDED",
} as const;
export type AccountingSalesorderStatus = OpenEnum<
  typeof AccountingSalesorderStatus
>;

export type AccountingSalesorder = {
  accountId?: string | undefined;
  billingAddress?: PropertyAccountingSalesorderBillingAddress | undefined;
  contactId?: string | undefined;
  createdAt?: Date | undefined;
  currency?: string | undefined;
  id?: string | undefined;
  lineitems?: Array<AccountingLineitem> | undefined;
  postedAt?: Date | undefined;
  raw?: { [k: string]: any } | undefined;
  salesChannel?: string | undefined;
  shippingAddress?: PropertyAccountingSalesorderShippingAddress | undefined;
  status?: AccountingSalesorderStatus | undefined;
  totalAmount?: number | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const AccountingSalesorderStatus$inboundSchema: z.ZodType<
  AccountingSalesorderStatus,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(AccountingSalesorderStatus),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const AccountingSalesorderStatus$outboundSchema: z.ZodType<
  AccountingSalesorderStatus,
  z.ZodTypeDef,
  AccountingSalesorderStatus
> = z.union([
  z.nativeEnum(AccountingSalesorderStatus),
  z.string().and(z.custom<Unrecognized<string>>()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountingSalesorderStatus$ {
  /** @deprecated use `AccountingSalesorderStatus$inboundSchema` instead. */
  export const inboundSchema = AccountingSalesorderStatus$inboundSchema;
  /** @deprecated use `AccountingSalesorderStatus$outboundSchema` instead. */
  export const outboundSchema = AccountingSalesorderStatus$outboundSchema;
}

/** @internal */
export const AccountingSalesorder$inboundSchema: z.ZodType<
  AccountingSalesorder,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_id: z.string().optional(),
  billing_address: PropertyAccountingSalesorderBillingAddress$inboundSchema
    .optional(),
  contact_id: z.string().optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  currency: z.string().optional(),
  id: z.string().optional(),
  lineitems: z.array(AccountingLineitem$inboundSchema).optional(),
  posted_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  raw: z.record(z.any()).optional(),
  sales_channel: z.string().optional(),
  shipping_address: PropertyAccountingSalesorderShippingAddress$inboundSchema
    .optional(),
  status: AccountingSalesorderStatus$inboundSchema.optional(),
  total_amount: z.number().optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "account_id": "accountId",
    "billing_address": "billingAddress",
    "contact_id": "contactId",
    "created_at": "createdAt",
    "posted_at": "postedAt",
    "sales_channel": "salesChannel",
    "shipping_address": "shippingAddress",
    "total_amount": "totalAmount",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type AccountingSalesorder$Outbound = {
  account_id?: string | undefined;
  billing_address?:
    | PropertyAccountingSalesorderBillingAddress$Outbound
    | undefined;
  contact_id?: string | undefined;
  created_at?: string | undefined;
  currency?: string | undefined;
  id?: string | undefined;
  lineitems?: Array<AccountingLineitem$Outbound> | undefined;
  posted_at?: string | undefined;
  raw?: { [k: string]: any } | undefined;
  sales_channel?: string | undefined;
  shipping_address?:
    | PropertyAccountingSalesorderShippingAddress$Outbound
    | undefined;
  status?: string | undefined;
  total_amount?: number | undefined;
  updated_at?: string | undefined;
};

/** @internal */
export const AccountingSalesorder$outboundSchema: z.ZodType<
  AccountingSalesorder$Outbound,
  z.ZodTypeDef,
  AccountingSalesorder
> = z.object({
  accountId: z.string().optional(),
  billingAddress: PropertyAccountingSalesorderBillingAddress$outboundSchema
    .optional(),
  contactId: z.string().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  currency: z.string().optional(),
  id: z.string().optional(),
  lineitems: z.array(AccountingLineitem$outboundSchema).optional(),
  postedAt: z.date().transform(v => v.toISOString()).optional(),
  raw: z.record(z.any()).optional(),
  salesChannel: z.string().optional(),
  shippingAddress: PropertyAccountingSalesorderShippingAddress$outboundSchema
    .optional(),
  status: AccountingSalesorderStatus$outboundSchema.optional(),
  totalAmount: z.number().optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    accountId: "account_id",
    billingAddress: "billing_address",
    contactId: "contact_id",
    createdAt: "created_at",
    postedAt: "posted_at",
    salesChannel: "sales_channel",
    shippingAddress: "shipping_address",
    totalAmount: "total_amount",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountingSalesorder$ {
  /** @deprecated use `AccountingSalesorder$inboundSchema` instead. */
  export const inboundSchema = AccountingSalesorder$inboundSchema;
  /** @deprecated use `AccountingSalesorder$outboundSchema` instead. */
  export const outboundSchema = AccountingSalesorder$outboundSchema;
  /** @deprecated use `AccountingSalesorder$Outbound` instead. */
  export type Outbound = AccountingSalesorder$Outbound;
}

export function accountingSalesorderToJSON(
  accountingSalesorder: AccountingSalesorder,
): string {
  return JSON.stringify(
    AccountingSalesorder$outboundSchema.parse(accountingSalesorder),
  );
}

export function accountingSalesorderFromJSON(
  jsonString: string,
): SafeParseResult<AccountingSalesorder, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountingSalesorder$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountingSalesorder' from JSON`,
  );
}
