/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DayOfWeek = {
  Monday: "MONDAY",
  Tuesday: "TUESDAY",
  Wednesday: "WEDNESDAY",
  Thursday: "THURSDAY",
  Friday: "FRIDAY",
  Saturday: "SATURDAY",
  Sunday: "SUNDAY",
} as const;
export type DayOfWeek = OpenEnum<typeof DayOfWeek>;

export type AdSchedule = {
  bidModifier?: number | undefined;
  dayOfWeek: DayOfWeek;
  endHour: number;
  endMinute?: number | undefined;
  startHour: number;
  startMinute?: number | undefined;
};

/** @internal */
export const DayOfWeek$inboundSchema: z.ZodType<
  DayOfWeek,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DayOfWeek);
/** @internal */
export const DayOfWeek$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  DayOfWeek
> = openEnums.outboundSchema(DayOfWeek);

/** @internal */
export const AdSchedule$inboundSchema: z.ZodType<
  AdSchedule,
  z.ZodTypeDef,
  unknown
> = z.object({
  bid_modifier: z.number().optional(),
  day_of_week: DayOfWeek$inboundSchema,
  end_hour: z.number(),
  end_minute: z.number().optional(),
  start_hour: z.number(),
  start_minute: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "bid_modifier": "bidModifier",
    "day_of_week": "dayOfWeek",
    "end_hour": "endHour",
    "end_minute": "endMinute",
    "start_hour": "startHour",
    "start_minute": "startMinute",
  });
});
/** @internal */
export type AdSchedule$Outbound = {
  bid_modifier?: number | undefined;
  day_of_week: string;
  end_hour: number;
  end_minute?: number | undefined;
  start_hour: number;
  start_minute?: number | undefined;
};

/** @internal */
export const AdSchedule$outboundSchema: z.ZodType<
  AdSchedule$Outbound,
  z.ZodTypeDef,
  AdSchedule
> = z.object({
  bidModifier: z.number().optional(),
  dayOfWeek: DayOfWeek$outboundSchema,
  endHour: z.number(),
  endMinute: z.number().optional(),
  startHour: z.number(),
  startMinute: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    bidModifier: "bid_modifier",
    dayOfWeek: "day_of_week",
    endHour: "end_hour",
    endMinute: "end_minute",
    startHour: "start_hour",
    startMinute: "start_minute",
  });
});

export function adScheduleToJSON(adSchedule: AdSchedule): string {
  return JSON.stringify(AdSchedule$outboundSchema.parse(adSchedule));
}
export function adScheduleFromJSON(
  jsonString: string,
): SafeParseResult<AdSchedule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdSchedule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdSchedule' from JSON`,
  );
}
