/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CommerceReservationStatus = {
  Pending: "PENDING",
  Confirmed: "CONFIRMED",
  Cancelled: "CANCELLED",
  NoShow: "NO_SHOW",
  Completed: "COMPLETED",
} as const;
export type CommerceReservationStatus = OpenEnum<
  typeof CommerceReservationStatus
>;

export type CommerceReservation = {
  createdAt?: Date | undefined;
  endAt?: Date | undefined;
  guestEmail?: string | undefined;
  guestName?: string | undefined;
  guestPhone?: string | undefined;
  id?: string | undefined;
  itemId?: string | undefined;
  itemName?: string | undefined;
  locationId?: string | undefined;
  notes?: string | undefined;
  raw?: { [k: string]: any } | undefined;
  size?: number | undefined;
  staffName?: string | undefined;
  staffUserId?: string | undefined;
  startAt?: Date | undefined;
  status?: CommerceReservationStatus | undefined;
  updatedAt?: Date | undefined;
  url?: string | undefined;
};

/** @internal */
export const CommerceReservationStatus$inboundSchema: z.ZodType<
  CommerceReservationStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CommerceReservationStatus);
/** @internal */
export const CommerceReservationStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  CommerceReservationStatus
> = openEnums.outboundSchema(CommerceReservationStatus);

/** @internal */
export const CommerceReservation$inboundSchema: z.ZodType<
  CommerceReservation,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  end_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  guest_email: z.string().optional(),
  guest_name: z.string().optional(),
  guest_phone: z.string().optional(),
  id: z.string().optional(),
  item_id: z.string().optional(),
  item_name: z.string().optional(),
  location_id: z.string().optional(),
  notes: z.string().optional(),
  raw: z.record(z.any()).optional(),
  size: z.number().optional(),
  staff_name: z.string().optional(),
  staff_user_id: z.string().optional(),
  start_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  status: CommerceReservationStatus$inboundSchema.optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "end_at": "endAt",
    "guest_email": "guestEmail",
    "guest_name": "guestName",
    "guest_phone": "guestPhone",
    "item_id": "itemId",
    "item_name": "itemName",
    "location_id": "locationId",
    "staff_name": "staffName",
    "staff_user_id": "staffUserId",
    "start_at": "startAt",
    "updated_at": "updatedAt",
  });
});
/** @internal */
export type CommerceReservation$Outbound = {
  created_at?: string | undefined;
  end_at?: string | undefined;
  guest_email?: string | undefined;
  guest_name?: string | undefined;
  guest_phone?: string | undefined;
  id?: string | undefined;
  item_id?: string | undefined;
  item_name?: string | undefined;
  location_id?: string | undefined;
  notes?: string | undefined;
  raw?: { [k: string]: any } | undefined;
  size?: number | undefined;
  staff_name?: string | undefined;
  staff_user_id?: string | undefined;
  start_at?: string | undefined;
  status?: string | undefined;
  updated_at?: string | undefined;
  url?: string | undefined;
};

/** @internal */
export const CommerceReservation$outboundSchema: z.ZodType<
  CommerceReservation$Outbound,
  z.ZodTypeDef,
  CommerceReservation
> = z.object({
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  endAt: z.date().transform(v => v.toISOString()).optional(),
  guestEmail: z.string().optional(),
  guestName: z.string().optional(),
  guestPhone: z.string().optional(),
  id: z.string().optional(),
  itemId: z.string().optional(),
  itemName: z.string().optional(),
  locationId: z.string().optional(),
  notes: z.string().optional(),
  raw: z.record(z.any()).optional(),
  size: z.number().optional(),
  staffName: z.string().optional(),
  staffUserId: z.string().optional(),
  startAt: z.date().transform(v => v.toISOString()).optional(),
  status: CommerceReservationStatus$outboundSchema.optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
  url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    endAt: "end_at",
    guestEmail: "guest_email",
    guestName: "guest_name",
    guestPhone: "guest_phone",
    itemId: "item_id",
    itemName: "item_name",
    locationId: "location_id",
    staffName: "staff_name",
    staffUserId: "staff_user_id",
    startAt: "start_at",
    updatedAt: "updated_at",
  });
});

export function commerceReservationToJSON(
  commerceReservation: CommerceReservation,
): string {
  return JSON.stringify(
    CommerceReservation$outboundSchema.parse(commerceReservation),
  );
}
export function commerceReservationFromJSON(
  jsonString: string,
): SafeParseResult<CommerceReservation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommerceReservation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommerceReservation' from JSON`,
  );
}
