/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CrmPicklistType = {
  Industry: "INDUSTRY",
} as const;
export type CrmPicklistType = OpenEnum<typeof CrmPicklistType>;

export type CrmPicklist = {
  id: string;
  label?: string | undefined;
  name?: string | undefined;
  raw?: { [k: string]: any } | undefined;
  type?: CrmPicklistType | undefined;
};

/** @internal */
export const CrmPicklistType$inboundSchema: z.ZodType<
  CrmPicklistType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CrmPicklistType);

/** @internal */
export const CrmPicklist$inboundSchema: z.ZodType<
  CrmPicklist,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  label: z.string().optional(),
  name: z.string().optional(),
  raw: z.record(z.any()).optional(),
  type: CrmPicklistType$inboundSchema.optional(),
});

export function crmPicklistFromJSON(
  jsonString: string,
): SafeParseResult<CrmPicklist, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CrmPicklist$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CrmPicklist' from JSON`,
  );
}
