/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PerformanceReviewQuestion,
  PerformanceReviewQuestion$inboundSchema,
} from "./performancereviewquestion.js";

export const PerformanceReviewStatus = {
  Draft: "DRAFT",
  InProgress: "IN_PROGRESS",
  Submitted: "SUBMITTED",
  Completed: "COMPLETED",
  Shared: "SHARED",
  Acknowledged: "ACKNOWLEDGED",
  Other: "OTHER",
} as const;
export type PerformanceReviewStatus = OpenEnum<typeof PerformanceReviewStatus>;

export const PerformanceReviewType = {
  Self: "SELF",
  Manager: "MANAGER",
  Peer: "PEER",
  Upward: "UPWARD",
  Other: "OTHER",
} as const;
export type PerformanceReviewType = OpenEnum<typeof PerformanceReviewType>;

export type PerformanceReview = {
  comment?: string | undefined;
  completedAt?: Date | undefined;
  createdAt?: Date | undefined;
  cycleId?: string | undefined;
  id?: string | undefined;
  isAcknowledged?: boolean | undefined;
  questions?: Array<PerformanceReviewQuestion> | undefined;
  rating?: number | undefined;
  ratingDescription?: string | undefined;
  ratingMaximum?: number | undefined;
  raw?: { [k: string]: any } | undefined;
  reviewerUserId?: string | undefined;
  status?: PerformanceReviewStatus | undefined;
  submittedAt?: Date | undefined;
  templateIdentifier?: string | undefined;
  type?: PerformanceReviewType | undefined;
  updatedAt?: Date | undefined;
  userId: string;
};

/** @internal */
export const PerformanceReviewStatus$inboundSchema: z.ZodType<
  PerformanceReviewStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(PerformanceReviewStatus);

/** @internal */
export const PerformanceReviewType$inboundSchema: z.ZodType<
  PerformanceReviewType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(PerformanceReviewType);

/** @internal */
export const PerformanceReview$inboundSchema: z.ZodType<
  PerformanceReview,
  z.ZodTypeDef,
  unknown
> = z.object({
  comment: z.string().optional(),
  completed_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  cycle_id: z.string().optional(),
  id: z.string().optional(),
  is_acknowledged: z.boolean().optional(),
  questions: z.array(PerformanceReviewQuestion$inboundSchema).optional(),
  rating: z.number().optional(),
  rating_description: z.string().optional(),
  rating_maximum: z.number().optional(),
  raw: z.record(z.any()).optional(),
  reviewer_user_id: z.string().optional(),
  status: PerformanceReviewStatus$inboundSchema.optional(),
  submitted_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  template_identifier: z.string().optional(),
  type: PerformanceReviewType$inboundSchema.optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  user_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "completed_at": "completedAt",
    "created_at": "createdAt",
    "cycle_id": "cycleId",
    "is_acknowledged": "isAcknowledged",
    "rating_description": "ratingDescription",
    "rating_maximum": "ratingMaximum",
    "reviewer_user_id": "reviewerUserId",
    "submitted_at": "submittedAt",
    "template_identifier": "templateIdentifier",
    "updated_at": "updatedAt",
    "user_id": "userId",
  });
});

export function performanceReviewFromJSON(
  jsonString: string,
): SafeParseResult<PerformanceReview, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PerformanceReview$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PerformanceReview' from JSON`,
  );
}
