/*
 * Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum PropertyUcCallTelephoneType {
    Work = "WORK",
    Home = "HOME",
    Other = "OTHER",
    Fax = "FAX",
    Mobile = "MOBILE",
}

/**
 * The telephone number called
 */
export class PropertyUcCallTelephone extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "telephone" })
    telephone: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: PropertyUcCallTelephoneType;
}
