/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PropertyAdsInsertionorderKpiType = {
  Unspecified: "UNSPECIFIED",
  Cpm: "CPM",
  Cpc: "CPC",
  Cpa: "CPA",
  Ctr: "CTR",
  Viewability: "VIEWABILITY",
  Cpiavc: "CPIAVC",
  Cpe: "CPE",
  Cpv: "CPV",
  ClickCvr: "CLICK_CVR",
  ImpressionCvr: "IMPRESSION_CVR",
  Vcpm: "VCPM",
  Vtr: "VTR",
  AudioCompletionRate: "AUDIO_COMPLETION_RATE",
  VideoCompletionRate: "VIDEO_COMPLETION_RATE",
  Cpcl: "CPCL",
  Cpcv: "CPCV",
  Tos10: "TOS10",
  MaximizePacing: "MAXIMIZE_PACING",
  CustomImpressionValueOverCost: "CUSTOM_IMPRESSION_VALUE_OVER_COST",
  Other: "OTHER",
} as const;
export type PropertyAdsInsertionorderKpiType = OpenEnum<
  typeof PropertyAdsInsertionorderKpiType
>;

export type PropertyAdsInsertionorderKpi = {
  algorithmId?: string | undefined;
  amount?: number | undefined;
  percentage?: number | undefined;
  stringValue?: string | undefined;
  type?: PropertyAdsInsertionorderKpiType | undefined;
};

/** @internal */
export const PropertyAdsInsertionorderKpiType$inboundSchema: z.ZodType<
  PropertyAdsInsertionorderKpiType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(PropertyAdsInsertionorderKpiType);
/** @internal */
export const PropertyAdsInsertionorderKpiType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  PropertyAdsInsertionorderKpiType
> = openEnums.outboundSchema(PropertyAdsInsertionorderKpiType);

/** @internal */
export const PropertyAdsInsertionorderKpi$inboundSchema: z.ZodType<
  PropertyAdsInsertionorderKpi,
  z.ZodTypeDef,
  unknown
> = z.object({
  algorithm_id: z.string().optional(),
  amount: z.number().optional(),
  percentage: z.number().optional(),
  string_value: z.string().optional(),
  type: PropertyAdsInsertionorderKpiType$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "algorithm_id": "algorithmId",
    "string_value": "stringValue",
  });
});
/** @internal */
export type PropertyAdsInsertionorderKpi$Outbound = {
  algorithm_id?: string | undefined;
  amount?: number | undefined;
  percentage?: number | undefined;
  string_value?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const PropertyAdsInsertionorderKpi$outboundSchema: z.ZodType<
  PropertyAdsInsertionorderKpi$Outbound,
  z.ZodTypeDef,
  PropertyAdsInsertionorderKpi
> = z.object({
  algorithmId: z.string().optional(),
  amount: z.number().optional(),
  percentage: z.number().optional(),
  stringValue: z.string().optional(),
  type: PropertyAdsInsertionorderKpiType$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    algorithmId: "algorithm_id",
    stringValue: "string_value",
  });
});

export function propertyAdsInsertionorderKpiToJSON(
  propertyAdsInsertionorderKpi: PropertyAdsInsertionorderKpi,
): string {
  return JSON.stringify(
    PropertyAdsInsertionorderKpi$outboundSchema.parse(
      propertyAdsInsertionorderKpi,
    ),
  );
}
export function propertyAdsInsertionorderKpiFromJSON(
  jsonString: string,
): SafeParseResult<PropertyAdsInsertionorderKpi, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PropertyAdsInsertionorderKpi$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PropertyAdsInsertionorderKpi' from JSON`,
  );
}
