/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const PropertyScimUserSchemas = {
  UrnIetfParamsScimSchemasCore20User:
    "urn:ietf:params:scim:schemas:core:2.0:User",
  UrnIetfParamsScimSchemasExtensionEnterprise20User:
    "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
  UrnIetfParamsScimSchemasExtensionLatticeAttributes10User:
    "urn:ietf:params:scim:schemas:extension:lattice:attributes:1.0:User",
  UrnIetfParamsScimSchemasExtensionPeakon20User:
    "urn:ietf:params:scim:schemas:extension:peakon:2.0:User",
} as const;
export type PropertyScimUserSchemas = ClosedEnum<
  typeof PropertyScimUserSchemas
>;

/** @internal */
export const PropertyScimUserSchemas$inboundSchema: z.ZodNativeEnum<
  typeof PropertyScimUserSchemas
> = z.nativeEnum(PropertyScimUserSchemas);

/** @internal */
export const PropertyScimUserSchemas$outboundSchema: z.ZodNativeEnum<
  typeof PropertyScimUserSchemas
> = PropertyScimUserSchemas$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PropertyScimUserSchemas$ {
  /** @deprecated use `PropertyScimUserSchemas$inboundSchema` instead. */
  export const inboundSchema = PropertyScimUserSchemas$inboundSchema;
  /** @deprecated use `PropertyScimUserSchemas$outboundSchema` instead. */
  export const outboundSchema = PropertyScimUserSchemas$outboundSchema;
}
