/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const PropertyIntegrationCategories = {
  Passthrough: "passthrough",
  Hris: "hris",
  Ats: "ats",
  Auth: "auth",
  Crm: "crm",
  Enrich: "enrich",
  Martech: "martech",
  Ticketing: "ticketing",
  Uc: "uc",
  Accounting: "accounting",
  Storage: "storage",
  Commerce: "commerce",
  Payment: "payment",
  Genai: "genai",
  Messaging: "messaging",
  Kms: "kms",
  Task: "task",
  Scim: "scim",
} as const;
export type PropertyIntegrationCategories = ClosedEnum<
  typeof PropertyIntegrationCategories
>;

/** @internal */
export const PropertyIntegrationCategories$inboundSchema: z.ZodNativeEnum<
  typeof PropertyIntegrationCategories
> = z.nativeEnum(PropertyIntegrationCategories);

/** @internal */
export const PropertyIntegrationCategories$outboundSchema: z.ZodNativeEnum<
  typeof PropertyIntegrationCategories
> = PropertyIntegrationCategories$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PropertyIntegrationCategories$ {
  /** @deprecated use `PropertyIntegrationCategories$inboundSchema` instead. */
  export const inboundSchema = PropertyIntegrationCategories$inboundSchema;
  /** @deprecated use `PropertyIntegrationCategories$outboundSchema` instead. */
  export const outboundSchema = PropertyIntegrationCategories$outboundSchema;
}
