/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PropertyAdsReportMetricsGroupFrequencyCapTimeUnit = {
  Unspecified: "UNSPECIFIED",
  Lifetime: "LIFETIME",
  Months: "MONTHS",
  Weeks: "WEEKS",
  Days: "DAYS",
  Hours: "HOURS",
  Minutes: "MINUTES",
} as const;
export type PropertyAdsReportMetricsGroupFrequencyCapTimeUnit = OpenEnum<
  typeof PropertyAdsReportMetricsGroupFrequencyCapTimeUnit
>;

export type PropertyAdsReportMetricsGroupFrequencyCap = {
  isUnlimited?: boolean | undefined;
  maxImpressions?: number | undefined;
  maxViews?: number | undefined;
  timeUnit?: PropertyAdsReportMetricsGroupFrequencyCapTimeUnit | undefined;
  timeUnitCount?: number | undefined;
};

/** @internal */
export const PropertyAdsReportMetricsGroupFrequencyCapTimeUnit$inboundSchema:
  z.ZodType<
    PropertyAdsReportMetricsGroupFrequencyCapTimeUnit,
    z.ZodTypeDef,
    unknown
  > = openEnums.inboundSchema(
    PropertyAdsReportMetricsGroupFrequencyCapTimeUnit,
  );

/** @internal */
export const PropertyAdsReportMetricsGroupFrequencyCap$inboundSchema: z.ZodType<
  PropertyAdsReportMetricsGroupFrequencyCap,
  z.ZodTypeDef,
  unknown
> = z.object({
  is_unlimited: z.boolean().optional(),
  max_impressions: z.number().optional(),
  max_views: z.number().optional(),
  time_unit: PropertyAdsReportMetricsGroupFrequencyCapTimeUnit$inboundSchema
    .optional(),
  time_unit_count: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "is_unlimited": "isUnlimited",
    "max_impressions": "maxImpressions",
    "max_views": "maxViews",
    "time_unit": "timeUnit",
    "time_unit_count": "timeUnitCount",
  });
});

export function propertyAdsReportMetricsGroupFrequencyCapFromJSON(
  jsonString: string,
): SafeParseResult<
  PropertyAdsReportMetricsGroupFrequencyCap,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PropertyAdsReportMetricsGroupFrequencyCap$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PropertyAdsReportMetricsGroupFrequencyCap' from JSON`,
  );
}
