/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PropertyAccountingBalancesheetItemSubItems = {};

/** @internal */
export const PropertyAccountingBalancesheetItemSubItems$inboundSchema:
  z.ZodType<PropertyAccountingBalancesheetItemSubItems, z.ZodTypeDef, unknown> =
    z.object({});

/** @internal */
export type PropertyAccountingBalancesheetItemSubItems$Outbound = {};

/** @internal */
export const PropertyAccountingBalancesheetItemSubItems$outboundSchema:
  z.ZodType<
    PropertyAccountingBalancesheetItemSubItems$Outbound,
    z.ZodTypeDef,
    PropertyAccountingBalancesheetItemSubItems
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PropertyAccountingBalancesheetItemSubItems$ {
  /** @deprecated use `PropertyAccountingBalancesheetItemSubItems$inboundSchema` instead. */
  export const inboundSchema =
    PropertyAccountingBalancesheetItemSubItems$inboundSchema;
  /** @deprecated use `PropertyAccountingBalancesheetItemSubItems$outboundSchema` instead. */
  export const outboundSchema =
    PropertyAccountingBalancesheetItemSubItems$outboundSchema;
  /** @deprecated use `PropertyAccountingBalancesheetItemSubItems$Outbound` instead. */
  export type Outbound = PropertyAccountingBalancesheetItemSubItems$Outbound;
}

export function propertyAccountingBalancesheetItemSubItemsToJSON(
  propertyAccountingBalancesheetItemSubItems:
    PropertyAccountingBalancesheetItemSubItems,
): string {
  return JSON.stringify(
    PropertyAccountingBalancesheetItemSubItems$outboundSchema.parse(
      propertyAccountingBalancesheetItemSubItems,
    ),
  );
}

export function propertyAccountingBalancesheetItemSubItemsFromJSON(
  jsonString: string,
): SafeParseResult<
  PropertyAccountingBalancesheetItemSubItems,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PropertyAccountingBalancesheetItemSubItems$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PropertyAccountingBalancesheetItemSubItems' from JSON`,
  );
}
