/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const PropertyAdsGroupTargetingContentVideoPlayerSizes = {
  Small: "SMALL",
  Large: "LARGE",
  Hd: "HD",
} as const;
export type PropertyAdsGroupTargetingContentVideoPlayerSizes = OpenEnum<
  typeof PropertyAdsGroupTargetingContentVideoPlayerSizes
>;

/** @internal */
export const PropertyAdsGroupTargetingContentVideoPlayerSizes$inboundSchema:
  z.ZodType<
    PropertyAdsGroupTargetingContentVideoPlayerSizes,
    z.ZodTypeDef,
    unknown
  > = openEnums.inboundSchema(PropertyAdsGroupTargetingContentVideoPlayerSizes);
/** @internal */
export const PropertyAdsGroupTargetingContentVideoPlayerSizes$outboundSchema:
  z.ZodType<
    string,
    z.ZodTypeDef,
    PropertyAdsGroupTargetingContentVideoPlayerSizes
  > = openEnums.outboundSchema(
    PropertyAdsGroupTargetingContentVideoPlayerSizes,
  );
