/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ShippingTrackingEvent,
  ShippingTrackingEvent$inboundSchema,
} from "./shippingtrackingevent.js";

export const ShippingTrackingStatus = {
  Pending: "PENDING",
  Processing: "PROCESSING",
  InTransit: "IN_TRANSIT",
  Delivered: "DELIVERED",
  Exception: "EXCEPTION",
  Cancelled: "CANCELLED",
  LabelCreated: "LABEL_CREATED",
  PickedUp: "PICKED_UP",
  OutForDelivery: "OUT_FOR_DELIVERY",
  DeliveryAttempted: "DELIVERY_ATTEMPTED",
  ReturnedToSender: "RETURNED_TO_SENDER",
  HeldAtLocation: "HELD_AT_LOCATION",
  CustomsClearance: "CUSTOMS_CLEARANCE",
  ExceptionResolved: "EXCEPTION_RESOLVED",
} as const;
export type ShippingTrackingStatus = OpenEnum<typeof ShippingTrackingStatus>;

export type ShippingTracking = {
  actualDeliveryAt?: Date | undefined;
  carrierId?: string | undefined;
  carrierStatusCode?: string | undefined;
  carrierStatusDescription?: string | undefined;
  createdAt?: Date | undefined;
  estimatedDelivery?: Date | undefined;
  /**
   * Array of tracking events
   */
  events?: Array<ShippingTrackingEvent> | undefined;
  id?: string | undefined;
  raw?: { [k: string]: any } | undefined;
  shipmentId?: string | undefined;
  status?: ShippingTrackingStatus | undefined;
  statusDescription?: string | undefined;
  trackingNumber?: string | undefined;
  updatedAt?: Date | undefined;
};

/** @internal */
export const ShippingTrackingStatus$inboundSchema: z.ZodType<
  ShippingTrackingStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ShippingTrackingStatus);

/** @internal */
export const ShippingTracking$inboundSchema: z.ZodType<
  ShippingTracking,
  z.ZodTypeDef,
  unknown
> = z.object({
  actual_delivery_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  carrier_id: z.string().optional(),
  carrier_status_code: z.string().optional(),
  carrier_status_description: z.string().optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  estimated_delivery: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  events: z.array(ShippingTrackingEvent$inboundSchema).optional(),
  id: z.string().optional(),
  raw: z.record(z.any()).optional(),
  shipment_id: z.string().optional(),
  status: ShippingTrackingStatus$inboundSchema.optional(),
  status_description: z.string().optional(),
  tracking_number: z.string().optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "actual_delivery_at": "actualDeliveryAt",
    "carrier_id": "carrierId",
    "carrier_status_code": "carrierStatusCode",
    "carrier_status_description": "carrierStatusDescription",
    "created_at": "createdAt",
    "estimated_delivery": "estimatedDelivery",
    "shipment_id": "shipmentId",
    "status_description": "statusDescription",
    "tracking_number": "trackingNumber",
    "updated_at": "updatedAt",
  });
});

export function shippingTrackingFromJSON(
  jsonString: string,
): SafeParseResult<ShippingTracking, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShippingTracking$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShippingTracking' from JSON`,
  );
}
