/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Undefined extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "support_url" })
    supportUrl?: string;
}
