/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";

export type CreateGenaiPromptRequest = {
  genaiPrompt?: shared.GenaiPrompt | undefined;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
};

/** @internal */
export const CreateGenaiPromptRequest$inboundSchema: z.ZodType<
  CreateGenaiPromptRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  GenaiPrompt: shared.GenaiPrompt$inboundSchema.optional(),
  connection_id: z.string(),
  fields: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "GenaiPrompt": "genaiPrompt",
    "connection_id": "connectionId",
  });
});

/** @internal */
export type CreateGenaiPromptRequest$Outbound = {
  GenaiPrompt?: shared.GenaiPrompt$Outbound | undefined;
  connection_id: string;
  fields?: Array<string> | undefined;
};

/** @internal */
export const CreateGenaiPromptRequest$outboundSchema: z.ZodType<
  CreateGenaiPromptRequest$Outbound,
  z.ZodTypeDef,
  CreateGenaiPromptRequest
> = z.object({
  genaiPrompt: shared.GenaiPrompt$outboundSchema.optional(),
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    genaiPrompt: "GenaiPrompt",
    connectionId: "connection_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateGenaiPromptRequest$ {
  /** @deprecated use `CreateGenaiPromptRequest$inboundSchema` instead. */
  export const inboundSchema = CreateGenaiPromptRequest$inboundSchema;
  /** @deprecated use `CreateGenaiPromptRequest$outboundSchema` instead. */
  export const outboundSchema = CreateGenaiPromptRequest$outboundSchema;
  /** @deprecated use `CreateGenaiPromptRequest$Outbound` instead. */
  export type Outbound = CreateGenaiPromptRequest$Outbound;
}
