/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const CreateAnalyticsVisitorQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  PropertyId: "property_id",
  Email: "email",
  Name: "name",
  Age: "age",
  Gender: "gender",
  Country: "country",
  CountryCode: "country_code",
  City: "city",
  Language: "language",
  Timezone: "timezone",
  FirstSeenAt: "first_seen_at",
  LastSeenAt: "last_seen_at",
  TotalSessions: "total_sessions",
  TotalPageViews: "total_page_views",
  TotalEvents: "total_events",
  Metadata: "metadata",
  Raw: "raw",
} as const;
export type CreateAnalyticsVisitorQueryParamFields = ClosedEnum<
  typeof CreateAnalyticsVisitorQueryParamFields
>;

export type CreateAnalyticsVisitorRequest = {
  analyticsVisitor: shared.AnalyticsVisitor;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<CreateAnalyticsVisitorQueryParamFields> | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const CreateAnalyticsVisitorQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof CreateAnalyticsVisitorQueryParamFields> = z.nativeEnum(
    CreateAnalyticsVisitorQueryParamFields,
  );

/** @internal */
export type CreateAnalyticsVisitorRequest$Outbound = {
  AnalyticsVisitor: shared.AnalyticsVisitor$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  raw?: string | undefined;
};

/** @internal */
export const CreateAnalyticsVisitorRequest$outboundSchema: z.ZodType<
  CreateAnalyticsVisitorRequest$Outbound,
  z.ZodTypeDef,
  CreateAnalyticsVisitorRequest
> = z.object({
  analyticsVisitor: shared.AnalyticsVisitor$outboundSchema,
  connectionId: z.string(),
  fields: z.array(CreateAnalyticsVisitorQueryParamFields$outboundSchema)
    .optional(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    analyticsVisitor: "AnalyticsVisitor",
    connectionId: "connection_id",
  });
});

export function createAnalyticsVisitorRequestToJSON(
  createAnalyticsVisitorRequest: CreateAnalyticsVisitorRequest,
): string {
  return JSON.stringify(
    CreateAnalyticsVisitorRequest$outboundSchema.parse(
      createAnalyticsVisitorRequest,
    ),
  );
}
