/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const CreateAccountingCategoryQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  Description: "description",
  IsActive: "is_active",
  ParentId: "parent_id",
  Raw: "raw",
} as const;
export type CreateAccountingCategoryQueryParamFields = ClosedEnum<
  typeof CreateAccountingCategoryQueryParamFields
>;

export type CreateAccountingCategoryRequest = {
  accountingCategory: shared.AccountingCategory;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<CreateAccountingCategoryQueryParamFields> | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const CreateAccountingCategoryQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof CreateAccountingCategoryQueryParamFields> = z
    .nativeEnum(CreateAccountingCategoryQueryParamFields);

/** @internal */
export type CreateAccountingCategoryRequest$Outbound = {
  AccountingCategory: shared.AccountingCategory$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  raw?: string | undefined;
};

/** @internal */
export const CreateAccountingCategoryRequest$outboundSchema: z.ZodType<
  CreateAccountingCategoryRequest$Outbound,
  z.ZodTypeDef,
  CreateAccountingCategoryRequest
> = z.object({
  accountingCategory: shared.AccountingCategory$outboundSchema,
  connectionId: z.string(),
  fields: z.array(CreateAccountingCategoryQueryParamFields$outboundSchema)
    .optional(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountingCategory: "AccountingCategory",
    connectionId: "connection_id",
  });
});

export function createAccountingCategoryRequestToJSON(
  createAccountingCategoryRequest: CreateAccountingCategoryRequest,
): string {
  return JSON.stringify(
    CreateAccountingCategoryRequest$outboundSchema.parse(
      createAccountingCategoryRequest,
    ),
  );
}
