/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const CreateHrisGroupQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  Description: "description",
  ParentId: "parent_id",
  Type: "type",
  UserIds: "user_ids",
  ManagerIds: "manager_ids",
  IsActive: "is_active",
  CompanyId: "company_id",
  Raw: "raw",
} as const;
export type CreateHrisGroupQueryParamFields = ClosedEnum<
  typeof CreateHrisGroupQueryParamFields
>;

export type CreateHrisGroupRequest = {
  hrisGroup: shared.HrisGroup;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<CreateHrisGroupQueryParamFields> | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const CreateHrisGroupQueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof CreateHrisGroupQueryParamFields
> = z.nativeEnum(CreateHrisGroupQueryParamFields);

/** @internal */
export type CreateHrisGroupRequest$Outbound = {
  HrisGroup: shared.HrisGroup$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  raw?: string | undefined;
};

/** @internal */
export const CreateHrisGroupRequest$outboundSchema: z.ZodType<
  CreateHrisGroupRequest$Outbound,
  z.ZodTypeDef,
  CreateHrisGroupRequest
> = z.object({
  hrisGroup: shared.HrisGroup$outboundSchema,
  connectionId: z.string(),
  fields: z.array(CreateHrisGroupQueryParamFields$outboundSchema).optional(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    hrisGroup: "HrisGroup",
    connectionId: "connection_id",
  });
});

export function createHrisGroupRequestToJSON(
  createHrisGroupRequest: CreateHrisGroupRequest,
): string {
  return JSON.stringify(
    CreateHrisGroupRequest$outboundSchema.parse(createHrisGroupRequest),
  );
}
