/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const CreateAccountingBankfeedaccountQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  OrganizationId: "organization_id",
  Name: "name",
  BankName: "bank_name",
  AccountNumber: "account_number",
  AccountNumberLast4: "account_number_last4",
  RoutingNumber: "routing_number",
  AccountType: "account_type",
  AccountId: "account_id",
  Currency: "currency",
  Balance: "balance",
  FeedStartAt: "feed_start_at",
  Status: "status",
  Raw: "raw",
} as const;
export type CreateAccountingBankfeedaccountQueryParamFields = ClosedEnum<
  typeof CreateAccountingBankfeedaccountQueryParamFields
>;

export type CreateAccountingBankfeedaccountRequest = {
  accountingBankfeedaccount: shared.AccountingBankfeedaccount;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<CreateAccountingBankfeedaccountQueryParamFields> | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const CreateAccountingBankfeedaccountQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof CreateAccountingBankfeedaccountQueryParamFields> = z
    .nativeEnum(CreateAccountingBankfeedaccountQueryParamFields);

/** @internal */
export type CreateAccountingBankfeedaccountRequest$Outbound = {
  AccountingBankfeedaccount: shared.AccountingBankfeedaccount$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  raw?: string | undefined;
};

/** @internal */
export const CreateAccountingBankfeedaccountRequest$outboundSchema: z.ZodType<
  CreateAccountingBankfeedaccountRequest$Outbound,
  z.ZodTypeDef,
  CreateAccountingBankfeedaccountRequest
> = z.object({
  accountingBankfeedaccount: shared.AccountingBankfeedaccount$outboundSchema,
  connectionId: z.string(),
  fields: z.array(
    CreateAccountingBankfeedaccountQueryParamFields$outboundSchema,
  ).optional(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountingBankfeedaccount: "AccountingBankfeedaccount",
    connectionId: "connection_id",
  });
});

export function createAccountingBankfeedaccountRequestToJSON(
  createAccountingBankfeedaccountRequest:
    CreateAccountingBankfeedaccountRequest,
): string {
  return JSON.stringify(
    CreateAccountingBankfeedaccountRequest$outboundSchema.parse(
      createAccountingBankfeedaccountRequest,
    ),
  );
}
