/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const CreateAccountingBill2QueryParamFields = {
  Id: "id",
  BillNumber: "bill_number",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  DueAt: "due_at",
  PaidAt: "paid_at",
  RefundedAt: "refunded_at",
  CancelledAt: "cancelled_at",
  PostedAt: "posted_at",
  TotalAmount: "total_amount",
  PaidAmount: "paid_amount",
  RefundAmount: "refund_amount",
  TaxAmount: "tax_amount",
  DiscountAmount: "discount_amount",
  BalanceAmount: "balance_amount",
  ContactId: "contact_id",
  Currency: "currency",
  Notes: "notes",
  RefundReason: "refund_reason",
  Lineitems: "lineitems",
  Status: "status",
  Url: "url",
  PaymentCollectionMethod: "payment_collection_method",
  Attachments: "attachments",
  Send: "send",
  OrganizationId: "organization_id",
  Raw: "raw",
} as const;
export type CreateAccountingBill2QueryParamFields = ClosedEnum<
  typeof CreateAccountingBill2QueryParamFields
>;

export type CreateAccountingBill2Request = {
  accountingBill: shared.AccountingBill;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<CreateAccountingBill2QueryParamFields> | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const CreateAccountingBill2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof CreateAccountingBill2QueryParamFields> = z.nativeEnum(
    CreateAccountingBill2QueryParamFields,
  );

/** @internal */
export type CreateAccountingBill2Request$Outbound = {
  AccountingBill: shared.AccountingBill$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  raw?: string | undefined;
};

/** @internal */
export const CreateAccountingBill2Request$outboundSchema: z.ZodType<
  CreateAccountingBill2Request$Outbound,
  z.ZodTypeDef,
  CreateAccountingBill2Request
> = z.object({
  accountingBill: shared.AccountingBill$outboundSchema,
  connectionId: z.string(),
  fields: z.array(CreateAccountingBill2QueryParamFields$outboundSchema)
    .optional(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountingBill: "AccountingBill",
    connectionId: "connection_id",
  });
});

export function createAccountingBill2RequestToJSON(
  createAccountingBill2Request: CreateAccountingBill2Request,
): string {
  return JSON.stringify(
    CreateAccountingBill2Request$outboundSchema.parse(
      createAccountingBill2Request,
    ),
  );
}
