/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";

export type CreateScimGroupsRequest = {
  group?: shared.Group | undefined;
  /**
   * ID of the connection
   */
  connectionId: string;
};

/** @internal */
export const CreateScimGroupsRequest$inboundSchema: z.ZodType<
  CreateScimGroupsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Group: shared.Group$inboundSchema.optional(),
  connection_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Group": "group",
    "connection_id": "connectionId",
  });
});

/** @internal */
export type CreateScimGroupsRequest$Outbound = {
  Group?: shared.Group$Outbound | undefined;
  connection_id: string;
};

/** @internal */
export const CreateScimGroupsRequest$outboundSchema: z.ZodType<
  CreateScimGroupsRequest$Outbound,
  z.ZodTypeDef,
  CreateScimGroupsRequest
> = z.object({
  group: shared.Group$outboundSchema.optional(),
  connectionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    group: "Group",
    connectionId: "connection_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateScimGroupsRequest$ {
  /** @deprecated use `CreateScimGroupsRequest$inboundSchema` instead. */
  export const inboundSchema = CreateScimGroupsRequest$inboundSchema;
  /** @deprecated use `CreateScimGroupsRequest$outboundSchema` instead. */
  export const outboundSchema = CreateScimGroupsRequest$outboundSchema;
  /** @deprecated use `CreateScimGroupsRequest$Outbound` instead. */
  export type Outbound = CreateScimGroupsRequest$Outbound;
}
