/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const CreateDatastoreTable2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  Description: "description",
  DatabaseId: "database_id",
  Fields: "fields",
  Relationships: "relationships",
  WebUrl: "web_url",
  ParentId: "parent_id",
  Raw: "raw",
} as const;
export type CreateDatastoreTable2QueryParamFields = ClosedEnum<
  typeof CreateDatastoreTable2QueryParamFields
>;

export type CreateDatastoreTable2Request = {
  datastoreTable: shared.DatastoreTable;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<CreateDatastoreTable2QueryParamFields> | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const CreateDatastoreTable2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof CreateDatastoreTable2QueryParamFields> = z.nativeEnum(
    CreateDatastoreTable2QueryParamFields,
  );

/** @internal */
export type CreateDatastoreTable2Request$Outbound = {
  DatastoreTable: shared.DatastoreTable$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  raw?: string | undefined;
};

/** @internal */
export const CreateDatastoreTable2Request$outboundSchema: z.ZodType<
  CreateDatastoreTable2Request$Outbound,
  z.ZodTypeDef,
  CreateDatastoreTable2Request
> = z.object({
  datastoreTable: shared.DatastoreTable$outboundSchema,
  connectionId: z.string(),
  fields: z.array(CreateDatastoreTable2QueryParamFields$outboundSchema)
    .optional(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    datastoreTable: "DatastoreTable",
    connectionId: "connection_id",
  });
});

export function createDatastoreTable2RequestToJSON(
  createDatastoreTable2Request: CreateDatastoreTable2Request,
): string {
  return JSON.stringify(
    CreateDatastoreTable2Request$outboundSchema.parse(
      createDatastoreTable2Request,
    ),
  );
}
