/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const CreateAdsCampaign2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  OrganizationId: "organization_id",
  Status: "status",
  StartAt: "start_at",
  EndAt: "end_at",
  BudgetAmount: "budget_amount",
  BudgetPeriod: "budget_period",
  TotalSpendAmount: "total_spend_amount",
  Targeting: "targeting",
  Goal: "goal",
  PlannedSpendAmount: "planned_spend_amount",
  FrequencyCap: "frequency_cap",
  AdvertisingChannelType: "advertising_channel_type",
  CampaignBudgetIdentifier: "campaign_budget_identifier",
  Currency: "currency",
  Category: "category",
  HasEuPoliticalAds: "has_eu_political_ads",
  Raw: "raw",
} as const;
export type CreateAdsCampaign2QueryParamFields = ClosedEnum<
  typeof CreateAdsCampaign2QueryParamFields
>;

export type CreateAdsCampaign2Request = {
  adsCampaign: shared.AdsCampaign;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<CreateAdsCampaign2QueryParamFields> | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const CreateAdsCampaign2QueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof CreateAdsCampaign2QueryParamFields
> = z.nativeEnum(CreateAdsCampaign2QueryParamFields);

/** @internal */
export type CreateAdsCampaign2Request$Outbound = {
  AdsCampaign: shared.AdsCampaign$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  raw?: string | undefined;
};

/** @internal */
export const CreateAdsCampaign2Request$outboundSchema: z.ZodType<
  CreateAdsCampaign2Request$Outbound,
  z.ZodTypeDef,
  CreateAdsCampaign2Request
> = z.object({
  adsCampaign: shared.AdsCampaign$outboundSchema,
  connectionId: z.string(),
  fields: z.array(CreateAdsCampaign2QueryParamFields$outboundSchema).optional(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    adsCampaign: "AdsCampaign",
    connectionId: "connection_id",
  });
});

export function createAdsCampaign2RequestToJSON(
  createAdsCampaign2Request: CreateAdsCampaign2Request,
): string {
  return JSON.stringify(
    CreateAdsCampaign2Request$outboundSchema.parse(createAdsCampaign2Request),
  );
}
