/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const CreateCommerceInventoryQueryParamFields = {
  Id: "id",
  UpdatedAt: "updated_at",
  ItemId: "item_id",
  ItemVariantId: "item_variant_id",
  ItemOptionId: "item_option_id",
  LocationId: "location_id",
  Available: "available",
  Raw: "raw",
} as const;
export type CreateCommerceInventoryQueryParamFields = ClosedEnum<
  typeof CreateCommerceInventoryQueryParamFields
>;

export type CreateCommerceInventoryRequest = {
  commerceInventory: shared.CommerceInventory;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<CreateCommerceInventoryQueryParamFields> | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const CreateCommerceInventoryQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof CreateCommerceInventoryQueryParamFields> = z
    .nativeEnum(CreateCommerceInventoryQueryParamFields);

/** @internal */
export type CreateCommerceInventoryRequest$Outbound = {
  CommerceInventory: shared.CommerceInventory$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  raw?: string | undefined;
};

/** @internal */
export const CreateCommerceInventoryRequest$outboundSchema: z.ZodType<
  CreateCommerceInventoryRequest$Outbound,
  z.ZodTypeDef,
  CreateCommerceInventoryRequest
> = z.object({
  commerceInventory: shared.CommerceInventory$outboundSchema,
  connectionId: z.string(),
  fields: z.array(CreateCommerceInventoryQueryParamFields$outboundSchema)
    .optional(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    commerceInventory: "CommerceInventory",
    connectionId: "connection_id",
  });
});

export function createCommerceInventoryRequestToJSON(
  createCommerceInventoryRequest: CreateCommerceInventoryRequest,
): string {
  return JSON.stringify(
    CreateCommerceInventoryRequest$outboundSchema.parse(
      createCommerceInventoryRequest,
    ),
  );
}
