/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const CreateAccountingOrder2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  PostedAt: "posted_at",
  ContactId: "contact_id",
  AccountId: "account_id",
  Type: "type",
  Currency: "currency",
  TotalAmount: "total_amount",
  ShippingAddress: "shipping_address",
  BillingAddress: "billing_address",
  Status: "status",
  Lineitems: "lineitems",
  Raw: "raw",
} as const;
export type CreateAccountingOrder2QueryParamFields = ClosedEnum<
  typeof CreateAccountingOrder2QueryParamFields
>;

export type CreateAccountingOrder2Request = {
  accountingOrder: shared.AccountingOrder;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<CreateAccountingOrder2QueryParamFields> | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const CreateAccountingOrder2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof CreateAccountingOrder2QueryParamFields> = z.nativeEnum(
    CreateAccountingOrder2QueryParamFields,
  );

/** @internal */
export type CreateAccountingOrder2Request$Outbound = {
  AccountingOrder: shared.AccountingOrder$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  raw?: string | undefined;
};

/** @internal */
export const CreateAccountingOrder2Request$outboundSchema: z.ZodType<
  CreateAccountingOrder2Request$Outbound,
  z.ZodTypeDef,
  CreateAccountingOrder2Request
> = z.object({
  accountingOrder: shared.AccountingOrder$outboundSchema,
  connectionId: z.string(),
  fields: z.array(CreateAccountingOrder2QueryParamFields$outboundSchema)
    .optional(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountingOrder: "AccountingOrder",
    connectionId: "connection_id",
  });
});

export function createAccountingOrder2RequestToJSON(
  createAccountingOrder2Request: CreateAccountingOrder2Request,
): string {
  return JSON.stringify(
    CreateAccountingOrder2Request$outboundSchema.parse(
      createAccountingOrder2Request,
    ),
  );
}
