/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetAccountingExpense2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  UserId: "user_id",
  ContactId: "contact_id",
  AccountId: "account_id",
  Name: "name",
  PaymentMethod: "payment_method",
  PostedAt: "posted_at",
  TotalAmount: "total_amount",
  Currency: "currency",
  TaxAmount: "tax_amount",
  ReimbursedAmount: "reimbursed_amount",
  ReimbursedAt: "reimbursed_at",
  ApprovedAt: "approved_at",
  ApproverUserId: "approver_user_id",
  Lineitems: "lineitems",
  Raw: "raw",
  OrganizationId: "organization_id",
} as const;
export type GetAccountingExpense2QueryParamFields = ClosedEnum<
  typeof GetAccountingExpense2QueryParamFields
>;

export type GetAccountingExpense2Request = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<GetAccountingExpense2QueryParamFields> | undefined;
  /**
   * ID of the Expense
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const GetAccountingExpense2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof GetAccountingExpense2QueryParamFields> = z.nativeEnum(
    GetAccountingExpense2QueryParamFields,
  );

/** @internal */
export type GetAccountingExpense2Request$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const GetAccountingExpense2Request$outboundSchema: z.ZodType<
  GetAccountingExpense2Request$Outbound,
  z.ZodTypeDef,
  GetAccountingExpense2Request
> = z.object({
  connectionId: z.string(),
  fields: z.array(GetAccountingExpense2QueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function getAccountingExpense2RequestToJSON(
  getAccountingExpense2Request: GetAccountingExpense2Request,
): string {
  return JSON.stringify(
    GetAccountingExpense2Request$outboundSchema.parse(
      getAccountingExpense2Request,
    ),
  );
}
