/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as z from "zod";

export type GetAtsActivityRequest = {
    /**
     * ID of the connection
     */
    connectionId: string;
    /**
     * Comma-delimited fields to return
     */
    fields?: Array<string> | undefined;
    /**
     * ID of the Activity
     */
    id: string;
};

/** @internal */
export const GetAtsActivityRequest$inboundSchema: z.ZodType<
    GetAtsActivityRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        connection_id: z.string(),
        fields: z.array(z.string()).optional(),
        id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            connection_id: "connectionId",
        });
    });

/** @internal */
export type GetAtsActivityRequest$Outbound = {
    connection_id: string;
    fields?: Array<string> | undefined;
    id: string;
};

/** @internal */
export const GetAtsActivityRequest$outboundSchema: z.ZodType<
    GetAtsActivityRequest$Outbound,
    z.ZodTypeDef,
    GetAtsActivityRequest
> = z
    .object({
        connectionId: z.string(),
        fields: z.array(z.string()).optional(),
        id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            connectionId: "connection_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAtsActivityRequest$ {
    /** @deprecated use `GetAtsActivityRequest$inboundSchema` instead. */
    export const inboundSchema = GetAtsActivityRequest$inboundSchema;
    /** @deprecated use `GetAtsActivityRequest$outboundSchema` instead. */
    export const outboundSchema = GetAtsActivityRequest$outboundSchema;
    /** @deprecated use `GetAtsActivityRequest$Outbound` instead. */
    export type Outbound = GetAtsActivityRequest$Outbound;
}
