/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetAdsInsertionorder2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  OrganizationId: "organization_id",
  CampaignId: "campaign_id",
  Status: "status",
  Pacing: "pacing",
  FrequencyCap: "frequency_cap",
  Kpi: "kpi",
  BudgetUnit: "budget_unit",
  BudgetSegments: "budget_segments",
  BidStrategy: "bid_strategy",
  Reference: "reference",
  Raw: "raw",
} as const;
export type GetAdsInsertionorder2QueryParamFields = ClosedEnum<
  typeof GetAdsInsertionorder2QueryParamFields
>;

export type GetAdsInsertionorder2Request = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<GetAdsInsertionorder2QueryParamFields> | undefined;
  /**
   * ID of the Insertionorder
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const GetAdsInsertionorder2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof GetAdsInsertionorder2QueryParamFields> = z.nativeEnum(
    GetAdsInsertionorder2QueryParamFields,
  );

/** @internal */
export type GetAdsInsertionorder2Request$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const GetAdsInsertionorder2Request$outboundSchema: z.ZodType<
  GetAdsInsertionorder2Request$Outbound,
  z.ZodTypeDef,
  GetAdsInsertionorder2Request
> = z.object({
  connectionId: z.string(),
  fields: z.array(GetAdsInsertionorder2QueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function getAdsInsertionorder2RequestToJSON(
  getAdsInsertionorder2Request: GetAdsInsertionorder2Request,
): string {
  return JSON.stringify(
    GetAdsInsertionorder2Request$outboundSchema.parse(
      getAdsInsertionorder2Request,
    ),
  );
}
