/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetAtsInterviewQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  CandidateId: "candidate_id",
  JobId: "job_id",
  ApplicationId: "application_id",
  UserIds: "user_ids",
  Status: "status",
  StartAt: "start_at",
  EndAt: "end_at",
  Location: "location",
  ExternalEventXref: "external_event_xref",
  Raw: "raw",
} as const;
export type GetAtsInterviewQueryParamFields = ClosedEnum<
  typeof GetAtsInterviewQueryParamFields
>;

export type GetAtsInterviewRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<GetAtsInterviewQueryParamFields> | undefined;
  /**
   * ID of the Interview
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const GetAtsInterviewQueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof GetAtsInterviewQueryParamFields
> = z.nativeEnum(GetAtsInterviewQueryParamFields);

/** @internal */
export type GetAtsInterviewRequest$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const GetAtsInterviewRequest$outboundSchema: z.ZodType<
  GetAtsInterviewRequest$Outbound,
  z.ZodTypeDef,
  GetAtsInterviewRequest
> = z.object({
  connectionId: z.string(),
  fields: z.array(GetAtsInterviewQueryParamFields$outboundSchema).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function getAtsInterviewRequestToJSON(
  getAtsInterviewRequest: GetAtsInterviewRequest,
): string {
  return JSON.stringify(
    GetAtsInterviewRequest$outboundSchema.parse(getAtsInterviewRequest),
  );
}
