/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetAdsCreative2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  CampaignId: "campaign_id",
  GroupId: "group_id",
  ItemId: "item_id",
  OrganizationId: "organization_id",
  Status: "status",
  CreativeType: "creative_type",
  HostingSource: "hosting_source",
  Width: "width",
  Height: "height",
  AssetUrls: "asset_urls",
  LinkUrl: "link_url",
  Body: "body",
  Title: "title",
  Cta: "cta",
  ThirdPartyTag: "third_party_tag",
  VastTagUrl: "vast_tag_url",
  ExternalCreativeReference: "external_creative_reference",
  ExternalPlacementReference: "external_placement_reference",
  ExternalAdReference: "external_ad_reference",
  Promoted: "promoted",
  Path1: "path1",
  Path2: "path2",
  Data: "data",
  Raw: "raw",
} as const;
export type GetAdsCreative2QueryParamFields = ClosedEnum<
  typeof GetAdsCreative2QueryParamFields
>;

export type GetAdsCreative2Request = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<GetAdsCreative2QueryParamFields> | undefined;
  /**
   * ID of the Creative
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const GetAdsCreative2QueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof GetAdsCreative2QueryParamFields
> = z.nativeEnum(GetAdsCreative2QueryParamFields);

/** @internal */
export type GetAdsCreative2Request$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const GetAdsCreative2Request$outboundSchema: z.ZodType<
  GetAdsCreative2Request$Outbound,
  z.ZodTypeDef,
  GetAdsCreative2Request
> = z.object({
  connectionId: z.string(),
  fields: z.array(GetAdsCreative2QueryParamFields$outboundSchema).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function getAdsCreative2RequestToJSON(
  getAdsCreative2Request: GetAdsCreative2Request,
): string {
  return JSON.stringify(
    GetAdsCreative2Request$outboundSchema.parse(getAdsCreative2Request),
  );
}
