/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAccountingTrialbalanceRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  /**
   * ID of the Trialbalance
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const GetAccountingTrialbalanceRequest$inboundSchema: z.ZodType<
  GetAccountingTrialbalanceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  connection_id: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "connection_id": "connectionId",
  });
});

/** @internal */
export type GetAccountingTrialbalanceRequest$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const GetAccountingTrialbalanceRequest$outboundSchema: z.ZodType<
  GetAccountingTrialbalanceRequest$Outbound,
  z.ZodTypeDef,
  GetAccountingTrialbalanceRequest
> = z.object({
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAccountingTrialbalanceRequest$ {
  /** @deprecated use `GetAccountingTrialbalanceRequest$inboundSchema` instead. */
  export const inboundSchema = GetAccountingTrialbalanceRequest$inboundSchema;
  /** @deprecated use `GetAccountingTrialbalanceRequest$outboundSchema` instead. */
  export const outboundSchema = GetAccountingTrialbalanceRequest$outboundSchema;
  /** @deprecated use `GetAccountingTrialbalanceRequest$Outbound` instead. */
  export type Outbound = GetAccountingTrialbalanceRequest$Outbound;
}

export function getAccountingTrialbalanceRequestToJSON(
  getAccountingTrialbalanceRequest: GetAccountingTrialbalanceRequest,
): string {
  return JSON.stringify(
    GetAccountingTrialbalanceRequest$outboundSchema.parse(
      getAccountingTrialbalanceRequest,
    ),
  );
}

export function getAccountingTrialbalanceRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountingTrialbalanceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountingTrialbalanceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountingTrialbalanceRequest' from JSON`,
  );
}
