/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetCrmLeadQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  FirstName: "first_name",
  LastName: "last_name",
  UserId: "user_id",
  CreatorUserId: "creator_user_id",
  ContactId: "contact_id",
  CompanyId: "company_id",
  CompanyName: "company_name",
  IsActive: "is_active",
  Address: "address",
  Emails: "emails",
  Telephones: "telephones",
  Source: "source",
  Status: "status",
  LinkUrls: "link_urls",
  Metadata: "metadata",
  Raw: "raw",
} as const;
export type GetCrmLeadQueryParamFields = ClosedEnum<
  typeof GetCrmLeadQueryParamFields
>;

export type GetCrmLeadRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<GetCrmLeadQueryParamFields> | undefined;
  /**
   * ID of the Lead
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const GetCrmLeadQueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof GetCrmLeadQueryParamFields
> = z.nativeEnum(GetCrmLeadQueryParamFields);

/** @internal */
export type GetCrmLeadRequest$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const GetCrmLeadRequest$outboundSchema: z.ZodType<
  GetCrmLeadRequest$Outbound,
  z.ZodTypeDef,
  GetCrmLeadRequest
> = z.object({
  connectionId: z.string(),
  fields: z.array(GetCrmLeadQueryParamFields$outboundSchema).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function getCrmLeadRequestToJSON(
  getCrmLeadRequest: GetCrmLeadRequest,
): string {
  return JSON.stringify(
    GetCrmLeadRequest$outboundSchema.parse(getCrmLeadRequest),
  );
}
