/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCrmEventRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  /**
   * ID of the Event
   */
  id: string;
};

/** @internal */
export const GetCrmEventRequest$inboundSchema: z.ZodType<
  GetCrmEventRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  connection_id: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "connection_id": "connectionId",
  });
});

/** @internal */
export type GetCrmEventRequest$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
};

/** @internal */
export const GetCrmEventRequest$outboundSchema: z.ZodType<
  GetCrmEventRequest$Outbound,
  z.ZodTypeDef,
  GetCrmEventRequest
> = z.object({
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCrmEventRequest$ {
  /** @deprecated use `GetCrmEventRequest$inboundSchema` instead. */
  export const inboundSchema = GetCrmEventRequest$inboundSchema;
  /** @deprecated use `GetCrmEventRequest$outboundSchema` instead. */
  export const outboundSchema = GetCrmEventRequest$outboundSchema;
  /** @deprecated use `GetCrmEventRequest$Outbound` instead. */
  export type Outbound = GetCrmEventRequest$Outbound;
}

export function getCrmEventRequestToJSON(
  getCrmEventRequest: GetCrmEventRequest,
): string {
  return JSON.stringify(
    GetCrmEventRequest$outboundSchema.parse(getCrmEventRequest),
  );
}

export function getCrmEventRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCrmEventRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCrmEventRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCrmEventRequest' from JSON`,
  );
}
