/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetCommerceItemQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  PublicName: "public_name",
  Slug: "slug",
  Description: "description",
  TaxrateId: "taxrate_id",
  GlobalCode: "global_code",
  PublicDescription: "public_description",
  IsActive: "is_active",
  IsTaxable: "is_taxable",
  VendorName: "vendor_name",
  Type: "type",
  Variants: "variants",
  Tags: "tags",
  Media: "media",
  CollectionIds: "collection_ids",
  AccountId: "account_id",
  Metadata: "metadata",
  Raw: "raw",
  Collections: "collections",
} as const;
export type GetCommerceItemQueryParamFields = ClosedEnum<
  typeof GetCommerceItemQueryParamFields
>;

export type GetCommerceItemRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<GetCommerceItemQueryParamFields> | undefined;
  /**
   * ID of the Item
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const GetCommerceItemQueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof GetCommerceItemQueryParamFields
> = z.nativeEnum(GetCommerceItemQueryParamFields);

/** @internal */
export type GetCommerceItemRequest$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const GetCommerceItemRequest$outboundSchema: z.ZodType<
  GetCommerceItemRequest$Outbound,
  z.ZodTypeDef,
  GetCommerceItemRequest
> = z.object({
  connectionId: z.string(),
  fields: z.array(GetCommerceItemQueryParamFields$outboundSchema).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function getCommerceItemRequestToJSON(
  getCommerceItemRequest: GetCommerceItemRequest,
): string {
  return JSON.stringify(
    GetCommerceItemRequest$outboundSchema.parse(getCommerceItemRequest),
  );
}
