/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCommerceInventoryRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  /**
   * ID of the Inventory
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const GetCommerceInventoryRequest$inboundSchema: z.ZodType<
  GetCommerceInventoryRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  connection_id: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "connection_id": "connectionId",
  });
});

/** @internal */
export type GetCommerceInventoryRequest$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const GetCommerceInventoryRequest$outboundSchema: z.ZodType<
  GetCommerceInventoryRequest$Outbound,
  z.ZodTypeDef,
  GetCommerceInventoryRequest
> = z.object({
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCommerceInventoryRequest$ {
  /** @deprecated use `GetCommerceInventoryRequest$inboundSchema` instead. */
  export const inboundSchema = GetCommerceInventoryRequest$inboundSchema;
  /** @deprecated use `GetCommerceInventoryRequest$outboundSchema` instead. */
  export const outboundSchema = GetCommerceInventoryRequest$outboundSchema;
  /** @deprecated use `GetCommerceInventoryRequest$Outbound` instead. */
  export type Outbound = GetCommerceInventoryRequest$Outbound;
}

export function getCommerceInventoryRequestToJSON(
  getCommerceInventoryRequest: GetCommerceInventoryRequest,
): string {
  return JSON.stringify(
    GetCommerceInventoryRequest$outboundSchema.parse(
      getCommerceInventoryRequest,
    ),
  );
}

export function getCommerceInventoryRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCommerceInventoryRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCommerceInventoryRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCommerceInventoryRequest' from JSON`,
  );
}
