/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetHrisDocumentQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  DocumentUrl: "document_url",
  DocumentData: "document_data",
  Filename: "filename",
  Type: "type",
  UserId: "user_id",
  CompanyId: "company_id",
  Raw: "raw",
} as const;
export type GetHrisDocumentQueryParamFields = ClosedEnum<
  typeof GetHrisDocumentQueryParamFields
>;

export type GetHrisDocumentRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<GetHrisDocumentQueryParamFields> | undefined;
  /**
   * ID of the Document
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const GetHrisDocumentQueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof GetHrisDocumentQueryParamFields
> = z.nativeEnum(GetHrisDocumentQueryParamFields);

/** @internal */
export type GetHrisDocumentRequest$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const GetHrisDocumentRequest$outboundSchema: z.ZodType<
  GetHrisDocumentRequest$Outbound,
  z.ZodTypeDef,
  GetHrisDocumentRequest
> = z.object({
  connectionId: z.string(),
  fields: z.array(GetHrisDocumentQueryParamFields$outboundSchema).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function getHrisDocumentRequestToJSON(
  getHrisDocumentRequest: GetHrisDocumentRequest,
): string {
  return JSON.stringify(
    GetHrisDocumentRequest$outboundSchema.parse(getHrisDocumentRequest),
  );
}
