/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetMessagingMessageQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  ChannelId: "channel_id",
  ChannelIds: "channel_ids",
  Channels: "channels",
  ParentId: "parent_id",
  RootMessageId: "root_message_id",
  MessageThreadIdentifier: "message_thread_identifier",
  AuthorMember: "author_member",
  DestinationMembers: "destination_members",
  HiddenMembers: "hidden_members",
  MentionedMembers: "mentioned_members",
  Reactions: "reactions",
  Subject: "subject",
  Message: "message",
  MessageHtml: "message_html",
  MessageMarkdown: "message_markdown",
  Attachments: "attachments",
  WebUrl: "web_url",
  Reference: "reference",
  HasChildren: "has_children",
  IsUnread: "is_unread",
  Buttons: "buttons",
  Raw: "raw",
} as const;
export type GetMessagingMessageQueryParamFields = ClosedEnum<
  typeof GetMessagingMessageQueryParamFields
>;

export type GetMessagingMessageRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<GetMessagingMessageQueryParamFields> | undefined;
  /**
   * ID of the Message
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const GetMessagingMessageQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof GetMessagingMessageQueryParamFields> = z.nativeEnum(
    GetMessagingMessageQueryParamFields,
  );

/** @internal */
export type GetMessagingMessageRequest$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const GetMessagingMessageRequest$outboundSchema: z.ZodType<
  GetMessagingMessageRequest$Outbound,
  z.ZodTypeDef,
  GetMessagingMessageRequest
> = z.object({
  connectionId: z.string(),
  fields: z.array(GetMessagingMessageQueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function getMessagingMessageRequestToJSON(
  getMessagingMessageRequest: GetMessagingMessageRequest,
): string {
  return JSON.stringify(
    GetMessagingMessageRequest$outboundSchema.parse(getMessagingMessageRequest),
  );
}
