/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type GetScimUsersRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * ID of the User
   */
  id: string;
};

/** @internal */
export type GetScimUsersRequest$Outbound = {
  connection_id: string;
  id: string;
};

/** @internal */
export const GetScimUsersRequest$outboundSchema: z.ZodType<
  GetScimUsersRequest$Outbound,
  z.ZodTypeDef,
  GetScimUsersRequest
> = z.object({
  connectionId: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function getScimUsersRequestToJSON(
  getScimUsersRequest: GetScimUsersRequest,
): string {
  return JSON.stringify(
    GetScimUsersRequest$outboundSchema.parse(getScimUsersRequest),
  );
}
