/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type ListCalendarEventsRequest = {
  /**
   * The calendar ID to filter by
   */
  calendarId?: string | undefined;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * The end date to filter by (deprecated)
   */
  endLe?: string | undefined;
  /**
   * The end date to filter by
   */
  endLt?: string | undefined;
  /**
   * Whether to flatten grouped or recurring items into individual entries.
   */
  expand?: boolean | undefined;
  /**
   * Whether to expand recurring calendar events
   */
  expandRecurringEvents?: boolean | undefined;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  /**
   * Query string to search. eg. email address or name
   */
  query?: string | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
  sort?: string | undefined;
  /**
   * The start date to filter by
   */
  startGte?: string | undefined;
  /**
   * Return only results whose updated date is equal or greater to this value
   */
  updatedGte?: string | undefined;
};

/** @internal */
export type ListCalendarEventsRequest$Outbound = {
  calendar_id?: string | undefined;
  connection_id: string;
  end_le?: string | undefined;
  end_lt?: string | undefined;
  expand?: boolean | undefined;
  expand_recurring_events?: boolean | undefined;
  fields?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  query?: string | undefined;
  raw?: string | undefined;
  sort?: string | undefined;
  start_gte?: string | undefined;
  updated_gte?: string | undefined;
};

/** @internal */
export const ListCalendarEventsRequest$outboundSchema: z.ZodType<
  ListCalendarEventsRequest$Outbound,
  z.ZodTypeDef,
  ListCalendarEventsRequest
> = z.object({
  calendarId: z.string().optional(),
  connectionId: z.string(),
  endLe: z.string().optional(),
  endLt: z.string().optional(),
  expand: z.boolean().optional(),
  expandRecurringEvents: z.boolean().optional(),
  fields: z.array(z.string()).optional(),
  limit: z.number().optional(),
  offset: z.number().optional(),
  order: z.string().optional(),
  query: z.string().optional(),
  raw: z.string().optional(),
  sort: z.string().optional(),
  startGte: z.string().optional(),
  updatedGte: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    calendarId: "calendar_id",
    connectionId: "connection_id",
    endLe: "end_le",
    endLt: "end_lt",
    expandRecurringEvents: "expand_recurring_events",
    startGte: "start_gte",
    updatedGte: "updated_gte",
  });
});

export function listCalendarEventsRequestToJSON(
  listCalendarEventsRequest: ListCalendarEventsRequest,
): string {
  return JSON.stringify(
    ListCalendarEventsRequest$outboundSchema.parse(listCalendarEventsRequest),
  );
}
