/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const ListVerificationRequests2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  PackageId: "package_id",
  Parameters: "parameters",
  TargetUrl: "target_url",
  CandidateId: "candidate_id",
  ProfileIpAddress: "profile_ip_address",
  ProfileName: "profile_name",
  ProfileDateOfBirth: "profile_date_of_birth",
  ProfileAddresses: "profile_addresses",
  ProfileGender: "profile_gender",
  ProfileEmails: "profile_emails",
  ProfileTelephones: "profile_telephones",
  ProfileNationalIdentifier: "profile_national_identifier",
  ResponseCompletedAt: "response_completed_at",
  ResponseExpiresAt: "response_expires_at",
  ResponseIssuedAt: "response_issued_at",
  ResponseStatus: "response_status",
  ResponseScore: "response_score",
  ResponseRedirectUrl: "response_redirect_url",
  ResponseDownloadUrls: "response_download_urls",
  ResponseDetails: "response_details",
  ResponseSource: "response_source",
  Raw: "raw",
} as const;
export type ListVerificationRequests2QueryParamFields = ClosedEnum<
  typeof ListVerificationRequests2QueryParamFields
>;

export type ListVerificationRequests2Request = {
  /**
   * The candidate ID to filter by
   */
  candidateId?: string | undefined;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<ListVerificationRequests2QueryParamFields> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  /**
   * The package ID to filter by
   */
  packageId?: string | undefined;
  /**
   * Query string to search. eg. email address or name
   */
  query?: string | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
  sort?: string | undefined;
  /**
   * Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
   */
  updatedGte?: string | undefined;
};

/** @internal */
export const ListVerificationRequests2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof ListVerificationRequests2QueryParamFields> = z
    .nativeEnum(ListVerificationRequests2QueryParamFields);

/** @internal */
export type ListVerificationRequests2Request$Outbound = {
  candidate_id?: string | undefined;
  connection_id: string;
  fields?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  package_id?: string | undefined;
  query?: string | undefined;
  raw?: string | undefined;
  sort?: string | undefined;
  updated_gte?: string | undefined;
};

/** @internal */
export const ListVerificationRequests2Request$outboundSchema: z.ZodType<
  ListVerificationRequests2Request$Outbound,
  z.ZodTypeDef,
  ListVerificationRequests2Request
> = z.object({
  candidateId: z.string().optional(),
  connectionId: z.string(),
  fields: z.array(ListVerificationRequests2QueryParamFields$outboundSchema)
    .optional(),
  limit: z.number().optional(),
  offset: z.number().optional(),
  order: z.string().optional(),
  packageId: z.string().optional(),
  query: z.string().optional(),
  raw: z.string().optional(),
  sort: z.string().optional(),
  updatedGte: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    candidateId: "candidate_id",
    connectionId: "connection_id",
    packageId: "package_id",
    updatedGte: "updated_gte",
  });
});

export function listVerificationRequests2RequestToJSON(
  listVerificationRequests2Request: ListVerificationRequests2Request,
): string {
  return JSON.stringify(
    ListVerificationRequests2Request$outboundSchema.parse(
      listVerificationRequests2Request,
    ),
  );
}
