/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as z from "zod";

export type ListCrmDealsRequest = {
    companyId?: string | undefined;
    /**
     * ID of the connection
     */
    connectionId: string;
    contactId?: string | undefined;
    /**
     * Comma-delimited fields to return
     */
    fields?: Array<string> | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    /**
     * Query string to search. eg. email address or name
     */
    query?: string | undefined;
    /**
     * Return only results whose updated date is equal or greater to this value
     */
    updatedGte?: Date | undefined;
    userId?: string | undefined;
};

/** @internal */
export const ListCrmDealsRequest$inboundSchema: z.ZodType<
    ListCrmDealsRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        company_id: z.string().optional(),
        connection_id: z.string(),
        contact_id: z.string().optional(),
        fields: z.array(z.string()).optional(),
        limit: z.number().optional(),
        offset: z.number().optional(),
        query: z.string().optional(),
        updated_gte: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        user_id: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            company_id: "companyId",
            connection_id: "connectionId",
            contact_id: "contactId",
            updated_gte: "updatedGte",
            user_id: "userId",
        });
    });

/** @internal */
export type ListCrmDealsRequest$Outbound = {
    company_id?: string | undefined;
    connection_id: string;
    contact_id?: string | undefined;
    fields?: Array<string> | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    query?: string | undefined;
    updated_gte?: string | undefined;
    user_id?: string | undefined;
};

/** @internal */
export const ListCrmDealsRequest$outboundSchema: z.ZodType<
    ListCrmDealsRequest$Outbound,
    z.ZodTypeDef,
    ListCrmDealsRequest
> = z
    .object({
        companyId: z.string().optional(),
        connectionId: z.string(),
        contactId: z.string().optional(),
        fields: z.array(z.string()).optional(),
        limit: z.number().optional(),
        offset: z.number().optional(),
        query: z.string().optional(),
        updatedGte: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        userId: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            companyId: "company_id",
            connectionId: "connection_id",
            contactId: "contact_id",
            updatedGte: "updated_gte",
            userId: "user_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCrmDealsRequest$ {
    /** @deprecated use `ListCrmDealsRequest$inboundSchema` instead. */
    export const inboundSchema = ListCrmDealsRequest$inboundSchema;
    /** @deprecated use `ListCrmDealsRequest$outboundSchema` instead. */
    export const outboundSchema = ListCrmDealsRequest$outboundSchema;
    /** @deprecated use `ListCrmDealsRequest$Outbound` instead. */
    export type Outbound = ListCrmDealsRequest$Outbound;
}
