/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type ListHrisEmployeesRequest = {
  /**
   * The company ID to filter by
   */
  companyId?: string | undefined;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  /**
   * Query string to search. eg. email address or name
   */
  query?: string | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
  sort?: string | undefined;
  /**
   * Return only results whose updated date is equal or greater to this value
   */
  updatedGte?: string | undefined;
};

/** @internal */
export type ListHrisEmployeesRequest$Outbound = {
  company_id?: string | undefined;
  connection_id: string;
  fields?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  query?: string | undefined;
  raw?: string | undefined;
  sort?: string | undefined;
  updated_gte?: string | undefined;
};

/** @internal */
export const ListHrisEmployeesRequest$outboundSchema: z.ZodType<
  ListHrisEmployeesRequest$Outbound,
  z.ZodTypeDef,
  ListHrisEmployeesRequest
> = z.object({
  companyId: z.string().optional(),
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
  limit: z.number().optional(),
  offset: z.number().optional(),
  order: z.string().optional(),
  query: z.string().optional(),
  raw: z.string().optional(),
  sort: z.string().optional(),
  updatedGte: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    companyId: "company_id",
    connectionId: "connection_id",
    updatedGte: "updated_gte",
  });
});

export function listHrisEmployeesRequestToJSON(
  listHrisEmployeesRequest: ListHrisEmployeesRequest,
): string {
  return JSON.stringify(
    ListHrisEmployeesRequest$outboundSchema.parse(listHrisEmployeesRequest),
  );
}
