/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const ListCrmCompaniesQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  DealIds: "deal_ids",
  ContactIds: "contact_ids",
  Emails: "emails",
  Telephones: "telephones",
  Websites: "websites",
  Address: "address",
  IsActive: "is_active",
  Tags: "tags",
  Description: "description",
  Industry: "industry",
  LinkUrls: "link_urls",
  Employees: "employees",
  Timezone: "timezone",
  UserId: "user_id",
  Metadata: "metadata",
  Domains: "domains",
  Raw: "raw",
} as const;
export type ListCrmCompaniesQueryParamFields = ClosedEnum<
  typeof ListCrmCompaniesQueryParamFields
>;

export type ListCrmCompaniesRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * The contact ID to filter by (reference to CrmContact)
   */
  contactId?: string | undefined;
  /**
   * The deal ID to filter by (reference to CrmDeal)
   */
  dealId?: string | undefined;
  /**
   * Fields to return
   */
  fields?: Array<ListCrmCompaniesQueryParamFields> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  /**
   * Query string to search. eg. email address or name
   */
  query?: string | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
  sort?: string | undefined;
  /**
   * Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
   */
  updatedGte?: string | undefined;
  /**
   * The user/employee ID to filter by (reference to HrisEmployee)
   */
  userId?: string | undefined;
};

/** @internal */
export const ListCrmCompaniesQueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof ListCrmCompaniesQueryParamFields
> = z.nativeEnum(ListCrmCompaniesQueryParamFields);

/** @internal */
export type ListCrmCompaniesRequest$Outbound = {
  connection_id: string;
  contact_id?: string | undefined;
  deal_id?: string | undefined;
  fields?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  query?: string | undefined;
  raw?: string | undefined;
  sort?: string | undefined;
  updated_gte?: string | undefined;
  user_id?: string | undefined;
};

/** @internal */
export const ListCrmCompaniesRequest$outboundSchema: z.ZodType<
  ListCrmCompaniesRequest$Outbound,
  z.ZodTypeDef,
  ListCrmCompaniesRequest
> = z.object({
  connectionId: z.string(),
  contactId: z.string().optional(),
  dealId: z.string().optional(),
  fields: z.array(ListCrmCompaniesQueryParamFields$outboundSchema).optional(),
  limit: z.number().optional(),
  offset: z.number().optional(),
  order: z.string().optional(),
  query: z.string().optional(),
  raw: z.string().optional(),
  sort: z.string().optional(),
  updatedGte: z.string().optional(),
  userId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
    contactId: "contact_id",
    dealId: "deal_id",
    updatedGte: "updated_gte",
    userId: "user_id",
  });
});

export function listCrmCompaniesRequestToJSON(
  listCrmCompaniesRequest: ListCrmCompaniesRequest,
): string {
  return JSON.stringify(
    ListCrmCompaniesRequest$outboundSchema.parse(listCrmCompaniesRequest),
  );
}
