/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const ListMartechCampaigns2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  Type: "type",
  Status: "status",
  ListIds: "list_ids",
  SubjectLine: "subject_line",
  PreviewText: "preview_text",
  FromName: "from_name",
  FromEmail: "from_email",
  ReplyToEmail: "reply_to_email",
  SendAt: "send_at",
  Raw: "raw",
} as const;
export type ListMartechCampaigns2QueryParamFields = ClosedEnum<
  typeof ListMartechCampaigns2QueryParamFields
>;

export type ListMartechCampaigns2Request = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<ListMartechCampaigns2QueryParamFields> | undefined;
  limit?: number | undefined;
  /**
   * The list ID to filter by
   */
  listId?: string | undefined;
  /**
   * The member ID to filter by
   */
  memberId?: string | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  /**
   * Query string to search. eg. email address or name
   */
  query?: string | undefined;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
  sort?: string | undefined;
  /**
   * Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
   */
  updatedGte?: string | undefined;
};

/** @internal */
export const ListMartechCampaigns2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof ListMartechCampaigns2QueryParamFields> = z.nativeEnum(
    ListMartechCampaigns2QueryParamFields,
  );

/** @internal */
export type ListMartechCampaigns2Request$Outbound = {
  connection_id: string;
  fields?: Array<string> | undefined;
  limit?: number | undefined;
  list_id?: string | undefined;
  member_id?: string | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  query?: string | undefined;
  raw?: string | undefined;
  sort?: string | undefined;
  updated_gte?: string | undefined;
};

/** @internal */
export const ListMartechCampaigns2Request$outboundSchema: z.ZodType<
  ListMartechCampaigns2Request$Outbound,
  z.ZodTypeDef,
  ListMartechCampaigns2Request
> = z.object({
  connectionId: z.string(),
  fields: z.array(ListMartechCampaigns2QueryParamFields$outboundSchema)
    .optional(),
  limit: z.number().optional(),
  listId: z.string().optional(),
  memberId: z.string().optional(),
  offset: z.number().optional(),
  order: z.string().optional(),
  query: z.string().optional(),
  raw: z.string().optional(),
  sort: z.string().optional(),
  updatedGte: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
    listId: "list_id",
    memberId: "member_id",
    updatedGte: "updated_gte",
  });
});

export function listMartechCampaigns2RequestToJSON(
  listMartechCampaigns2Request: ListMartechCampaigns2Request,
): string {
  return JSON.stringify(
    ListMartechCampaigns2Request$outboundSchema.parse(
      listMartechCampaigns2Request,
    ),
  );
}
