/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const PatchSigningSignatoryQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  DocumentId: "document_id",
  Name: "name",
  Email: "email",
  Role: "role",
  Status: "status",
  Order: "order",
  SignedAt: "signed_at",
  DeclineReason: "decline_reason",
  Raw: "raw",
} as const;
export type PatchSigningSignatoryQueryParamFields = ClosedEnum<
  typeof PatchSigningSignatoryQueryParamFields
>;

export type PatchSigningSignatoryRequest = {
  signingSignatory: shared.SigningSignatory;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<PatchSigningSignatoryQueryParamFields> | undefined;
  /**
   * ID of the Signatory
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const PatchSigningSignatoryQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof PatchSigningSignatoryQueryParamFields> = z.nativeEnum(
    PatchSigningSignatoryQueryParamFields,
  );

/** @internal */
export type PatchSigningSignatoryRequest$Outbound = {
  SigningSignatory: shared.SigningSignatory$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchSigningSignatoryRequest$outboundSchema: z.ZodType<
  PatchSigningSignatoryRequest$Outbound,
  z.ZodTypeDef,
  PatchSigningSignatoryRequest
> = z.object({
  signingSignatory: shared.SigningSignatory$outboundSchema,
  connectionId: z.string(),
  fields: z.array(PatchSigningSignatoryQueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    signingSignatory: "SigningSignatory",
    connectionId: "connection_id",
  });
});

export function patchSigningSignatoryRequestToJSON(
  patchSigningSignatoryRequest: PatchSigningSignatoryRequest,
): string {
  return JSON.stringify(
    PatchSigningSignatoryRequest$outboundSchema.parse(
      patchSigningSignatoryRequest,
    ),
  );
}
