/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const PatchMartechMemberQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  FirstName: "first_name",
  LastName: "last_name",
  Emails: "emails",
  ListIds: "list_ids",
  Tags: "tags",
  Raw: "raw",
} as const;
export type PatchMartechMemberQueryParamFields = ClosedEnum<
  typeof PatchMartechMemberQueryParamFields
>;

export type PatchMartechMemberRequest = {
  /**
   * A member represents a person
   */
  marketingMember: shared.MarketingMember;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<PatchMartechMemberQueryParamFields> | undefined;
  /**
   * ID of the Member
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const PatchMartechMemberQueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof PatchMartechMemberQueryParamFields
> = z.nativeEnum(PatchMartechMemberQueryParamFields);

/** @internal */
export type PatchMartechMemberRequest$Outbound = {
  MarketingMember: shared.MarketingMember$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchMartechMemberRequest$outboundSchema: z.ZodType<
  PatchMartechMemberRequest$Outbound,
  z.ZodTypeDef,
  PatchMartechMemberRequest
> = z.object({
  marketingMember: shared.MarketingMember$outboundSchema,
  connectionId: z.string(),
  fields: z.array(PatchMartechMemberQueryParamFields$outboundSchema).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    marketingMember: "MarketingMember",
    connectionId: "connection_id",
  });
});

export function patchMartechMemberRequestToJSON(
  patchMartechMemberRequest: PatchMartechMemberRequest,
): string {
  return JSON.stringify(
    PatchMartechMemberRequest$outboundSchema.parse(patchMartechMemberRequest),
  );
}
