/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const PatchLmsCollectionQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  Description: "description",
  Media: "media",
  IsActive: "is_active",
  ParentId: "parent_id",
  Raw: "raw",
} as const;
export type PatchLmsCollectionQueryParamFields = ClosedEnum<
  typeof PatchLmsCollectionQueryParamFields
>;

export type PatchLmsCollectionRequest = {
  lmsCollection: shared.LmsCollection;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<PatchLmsCollectionQueryParamFields> | undefined;
  /**
   * ID of the Collection
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const PatchLmsCollectionQueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof PatchLmsCollectionQueryParamFields
> = z.nativeEnum(PatchLmsCollectionQueryParamFields);

/** @internal */
export type PatchLmsCollectionRequest$Outbound = {
  LmsCollection: shared.LmsCollection$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchLmsCollectionRequest$outboundSchema: z.ZodType<
  PatchLmsCollectionRequest$Outbound,
  z.ZodTypeDef,
  PatchLmsCollectionRequest
> = z.object({
  lmsCollection: shared.LmsCollection$outboundSchema,
  connectionId: z.string(),
  fields: z.array(PatchLmsCollectionQueryParamFields$outboundSchema).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    lmsCollection: "LmsCollection",
    connectionId: "connection_id",
  });
});

export function patchLmsCollectionRequestToJSON(
  patchLmsCollectionRequest: PatchLmsCollectionRequest,
): string {
  return JSON.stringify(
    PatchLmsCollectionRequest$outboundSchema.parse(patchLmsCollectionRequest),
  );
}
