/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const PatchCommerceItemvariantQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  Items: "items",
  PublicName: "public_name",
  Description: "description",
  PublicDescription: "public_description",
  Sku: "sku",
  IsActive: "is_active",
  IsVisible: "is_visible",
  IsFeatured: "is_featured",
  Media: "media",
  AvailableAt: "available_at",
  Tags: "tags",
  Width: "width",
  Height: "height",
  Length: "length",
  Weight: "weight",
  SizeUnit: "size_unit",
  WeightUnit: "weight_unit",
  TotalStock: "total_stock",
  Prices: "prices",
  Options: "options",
  InventoryId: "inventory_id",
  RequiresShipping: "requires_shipping",
  Metadata: "metadata",
  Raw: "raw",
} as const;
export type PatchCommerceItemvariantQueryParamFields = ClosedEnum<
  typeof PatchCommerceItemvariantQueryParamFields
>;

export type PatchCommerceItemvariantRequest = {
  commerceItemvariant: shared.CommerceItemvariant1;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<PatchCommerceItemvariantQueryParamFields> | undefined;
  /**
   * ID of the Itemvariant
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const PatchCommerceItemvariantQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof PatchCommerceItemvariantQueryParamFields> = z
    .nativeEnum(PatchCommerceItemvariantQueryParamFields);

/** @internal */
export type PatchCommerceItemvariantRequest$Outbound = {
  CommerceItemvariant: shared.CommerceItemvariant1$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchCommerceItemvariantRequest$outboundSchema: z.ZodType<
  PatchCommerceItemvariantRequest$Outbound,
  z.ZodTypeDef,
  PatchCommerceItemvariantRequest
> = z.object({
  commerceItemvariant: shared.CommerceItemvariant1$outboundSchema,
  connectionId: z.string(),
  fields: z.array(PatchCommerceItemvariantQueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    commerceItemvariant: "CommerceItemvariant",
    connectionId: "connection_id",
  });
});

export function patchCommerceItemvariantRequestToJSON(
  patchCommerceItemvariantRequest: PatchCommerceItemvariantRequest,
): string {
  return JSON.stringify(
    PatchCommerceItemvariantRequest$outboundSchema.parse(
      patchCommerceItemvariantRequest,
    ),
  );
}
