/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const PatchCdpEventQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  Name: "name",
  Type: "type",
  OccurredAt: "occurred_at",
  ProfileId: "profile_id",
  Identifiers: "identifiers",
  Metadata: "metadata",
  Source: "source",
  SourceId: "source_id",
  Raw: "raw",
} as const;
export type PatchCdpEventQueryParamFields = ClosedEnum<
  typeof PatchCdpEventQueryParamFields
>;

export type PatchCdpEventRequest = {
  cdpEvent: shared.CdpEvent;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<PatchCdpEventQueryParamFields> | undefined;
  /**
   * ID of the Event
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const PatchCdpEventQueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof PatchCdpEventQueryParamFields
> = z.nativeEnum(PatchCdpEventQueryParamFields);

/** @internal */
export type PatchCdpEventRequest$Outbound = {
  CdpEvent: shared.CdpEvent$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchCdpEventRequest$outboundSchema: z.ZodType<
  PatchCdpEventRequest$Outbound,
  z.ZodTypeDef,
  PatchCdpEventRequest
> = z.object({
  cdpEvent: shared.CdpEvent$outboundSchema,
  connectionId: z.string(),
  fields: z.array(PatchCdpEventQueryParamFields$outboundSchema).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cdpEvent: "CdpEvent",
    connectionId: "connection_id",
  });
});

export function patchCdpEventRequestToJSON(
  patchCdpEventRequest: PatchCdpEventRequest,
): string {
  return JSON.stringify(
    PatchCdpEventRequest$outboundSchema.parse(patchCdpEventRequest),
  );
}
