/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const PatchCommerceReviewQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  ItemId: "item_id",
  ItemVariantId: "item_variant_id",
  Rating: "rating",
  Title: "title",
  Content: "content",
  AuthorName: "author_name",
  AuthorEmail: "author_email",
  AuthorAvatarUrl: "author_avatar_url",
  AuthorLocation: "author_location",
  VerifiedPurchase: "verified_purchase",
  HelpfulVotes: "helpful_votes",
  UnhelpfulVotes: "unhelpful_votes",
  Media: "media",
  Status: "status",
  IsVerified: "is_verified",
  IsFeatured: "is_featured",
  IsPublic: "is_public",
  Comments: "comments",
  Metadata: "metadata",
  Raw: "raw",
} as const;
export type PatchCommerceReviewQueryParamFields = ClosedEnum<
  typeof PatchCommerceReviewQueryParamFields
>;

export type PatchCommerceReviewRequest = {
  commerceReview: shared.CommerceReview;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<PatchCommerceReviewQueryParamFields> | undefined;
  /**
   * ID of the Review
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const PatchCommerceReviewQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof PatchCommerceReviewQueryParamFields> = z.nativeEnum(
    PatchCommerceReviewQueryParamFields,
  );

/** @internal */
export type PatchCommerceReviewRequest$Outbound = {
  CommerceReview: shared.CommerceReview$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchCommerceReviewRequest$outboundSchema: z.ZodType<
  PatchCommerceReviewRequest$Outbound,
  z.ZodTypeDef,
  PatchCommerceReviewRequest
> = z.object({
  commerceReview: shared.CommerceReview$outboundSchema,
  connectionId: z.string(),
  fields: z.array(PatchCommerceReviewQueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    commerceReview: "CommerceReview",
    connectionId: "connection_id",
  });
});

export function patchCommerceReviewRequestToJSON(
  patchCommerceReviewRequest: PatchCommerceReviewRequest,
): string {
  return JSON.stringify(
    PatchCommerceReviewRequest$outboundSchema.parse(patchCommerceReviewRequest),
  );
}
