/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const PatchKmsCommentQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Type: "type",
  ContentType: "content_type",
  Content: "content",
  UserId: "user_id",
  PageId: "page_id",
  ParentId: "parent_id",
  Raw: "raw",
} as const;
export type PatchKmsCommentQueryParamFields = ClosedEnum<
  typeof PatchKmsCommentQueryParamFields
>;

export type PatchKmsCommentRequest = {
  kmsComment: shared.KmsComment;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<PatchKmsCommentQueryParamFields> | undefined;
  /**
   * ID of the Comment
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const PatchKmsCommentQueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof PatchKmsCommentQueryParamFields
> = z.nativeEnum(PatchKmsCommentQueryParamFields);

/** @internal */
export type PatchKmsCommentRequest$Outbound = {
  KmsComment: shared.KmsComment$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchKmsCommentRequest$outboundSchema: z.ZodType<
  PatchKmsCommentRequest$Outbound,
  z.ZodTypeDef,
  PatchKmsCommentRequest
> = z.object({
  kmsComment: shared.KmsComment$outboundSchema,
  connectionId: z.string(),
  fields: z.array(PatchKmsCommentQueryParamFields$outboundSchema).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    kmsComment: "KmsComment",
    connectionId: "connection_id",
  });
});

export function patchKmsCommentRequestToJSON(
  patchKmsCommentRequest: PatchKmsCommentRequest,
): string {
  return JSON.stringify(
    PatchKmsCommentRequest$outboundSchema.parse(patchKmsCommentRequest),
  );
}
