/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";

export type PatchMetadataMetadataRequest = {
  metadataMetadata: shared.MetadataMetadata;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  /**
   * ID of the Metadata
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export type PatchMetadataMetadataRequest$Outbound = {
  MetadataMetadata: shared.MetadataMetadata$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchMetadataMetadataRequest$outboundSchema: z.ZodType<
  PatchMetadataMetadataRequest$Outbound,
  z.ZodTypeDef,
  PatchMetadataMetadataRequest
> = z.object({
  metadataMetadata: shared.MetadataMetadata$outboundSchema,
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    metadataMetadata: "MetadataMetadata",
    connectionId: "connection_id",
  });
});

export function patchMetadataMetadataRequestToJSON(
  patchMetadataMetadataRequest: PatchMetadataMetadataRequest,
): string {
  return JSON.stringify(
    PatchMetadataMetadataRequest$outboundSchema.parse(
      patchMetadataMetadataRequest,
    ),
  );
}
