/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const PatchCommerceSaleschannel2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Slug: "slug",
  Description: "description",
  IsActive: "is_active",
  Collections: "collections",
  Raw: "raw",
} as const;
export type PatchCommerceSaleschannel2QueryParamFields = ClosedEnum<
  typeof PatchCommerceSaleschannel2QueryParamFields
>;

export type PatchCommerceSaleschannel2Request = {
  commerceSaleschannel: shared.CommerceSaleschannel;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<PatchCommerceSaleschannel2QueryParamFields> | undefined;
  /**
   * ID of the Saleschannel
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const PatchCommerceSaleschannel2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof PatchCommerceSaleschannel2QueryParamFields> = z
    .nativeEnum(PatchCommerceSaleschannel2QueryParamFields);

/** @internal */
export type PatchCommerceSaleschannel2Request$Outbound = {
  CommerceSaleschannel: shared.CommerceSaleschannel$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchCommerceSaleschannel2Request$outboundSchema: z.ZodType<
  PatchCommerceSaleschannel2Request$Outbound,
  z.ZodTypeDef,
  PatchCommerceSaleschannel2Request
> = z.object({
  commerceSaleschannel: shared.CommerceSaleschannel$outboundSchema,
  connectionId: z.string(),
  fields: z.array(PatchCommerceSaleschannel2QueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    commerceSaleschannel: "CommerceSaleschannel",
    connectionId: "connection_id",
  });
});

export function patchCommerceSaleschannel2RequestToJSON(
  patchCommerceSaleschannel2Request: PatchCommerceSaleschannel2Request,
): string {
  return JSON.stringify(
    PatchCommerceSaleschannel2Request$outboundSchema.parse(
      patchCommerceSaleschannel2Request,
    ),
  );
}
