/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type PatchAccountingBillRequest = {
  accountingBill: shared.AccountingBill;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  /**
   * ID of the Bill
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const PatchAccountingBillRequest$inboundSchema: z.ZodType<
  PatchAccountingBillRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountingBill: shared.AccountingBill$inboundSchema,
  connection_id: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountingBill": "accountingBill",
    "connection_id": "connectionId",
  });
});

/** @internal */
export type PatchAccountingBillRequest$Outbound = {
  AccountingBill: shared.AccountingBill$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchAccountingBillRequest$outboundSchema: z.ZodType<
  PatchAccountingBillRequest$Outbound,
  z.ZodTypeDef,
  PatchAccountingBillRequest
> = z.object({
  accountingBill: shared.AccountingBill$outboundSchema,
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountingBill: "AccountingBill",
    connectionId: "connection_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchAccountingBillRequest$ {
  /** @deprecated use `PatchAccountingBillRequest$inboundSchema` instead. */
  export const inboundSchema = PatchAccountingBillRequest$inboundSchema;
  /** @deprecated use `PatchAccountingBillRequest$outboundSchema` instead. */
  export const outboundSchema = PatchAccountingBillRequest$outboundSchema;
  /** @deprecated use `PatchAccountingBillRequest$Outbound` instead. */
  export type Outbound = PatchAccountingBillRequest$Outbound;
}

export function patchAccountingBillRequestToJSON(
  patchAccountingBillRequest: PatchAccountingBillRequest,
): string {
  return JSON.stringify(
    PatchAccountingBillRequest$outboundSchema.parse(patchAccountingBillRequest),
  );
}

export function patchAccountingBillRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchAccountingBillRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchAccountingBillRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchAccountingBillRequest' from JSON`,
  );
}
