/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type PatchAccountingAccountRequest = {
  /**
   * Chart of accounts
   */
  accountingAccount: shared.AccountingAccount;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  /**
   * ID of the Account
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const PatchAccountingAccountRequest$inboundSchema: z.ZodType<
  PatchAccountingAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountingAccount: shared.AccountingAccount$inboundSchema,
  connection_id: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountingAccount": "accountingAccount",
    "connection_id": "connectionId",
  });
});

/** @internal */
export type PatchAccountingAccountRequest$Outbound = {
  AccountingAccount: shared.AccountingAccount$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const PatchAccountingAccountRequest$outboundSchema: z.ZodType<
  PatchAccountingAccountRequest$Outbound,
  z.ZodTypeDef,
  PatchAccountingAccountRequest
> = z.object({
  accountingAccount: shared.AccountingAccount$outboundSchema,
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountingAccount: "AccountingAccount",
    connectionId: "connection_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchAccountingAccountRequest$ {
  /** @deprecated use `PatchAccountingAccountRequest$inboundSchema` instead. */
  export const inboundSchema = PatchAccountingAccountRequest$inboundSchema;
  /** @deprecated use `PatchAccountingAccountRequest$outboundSchema` instead. */
  export const outboundSchema = PatchAccountingAccountRequest$outboundSchema;
  /** @deprecated use `PatchAccountingAccountRequest$Outbound` instead. */
  export type Outbound = PatchAccountingAccountRequest$Outbound;
}

export function patchAccountingAccountRequestToJSON(
  patchAccountingAccountRequest: PatchAccountingAccountRequest,
): string {
  return JSON.stringify(
    PatchAccountingAccountRequest$outboundSchema.parse(
      patchAccountingAccountRequest,
    ),
  );
}

export function patchAccountingAccountRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchAccountingAccountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchAccountingAccountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchAccountingAccountRequest' from JSON`,
  );
}
