/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemoveCommerceReservationRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * ID of the Reservation
   */
  id: string;
};

export type RemoveCommerceReservationResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type RemoveCommerceReservationRequest$Outbound = {
  connection_id: string;
  id: string;
};

/** @internal */
export const RemoveCommerceReservationRequest$outboundSchema: z.ZodType<
  RemoveCommerceReservationRequest$Outbound,
  z.ZodTypeDef,
  RemoveCommerceReservationRequest
> = z.object({
  connectionId: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function removeCommerceReservationRequestToJSON(
  removeCommerceReservationRequest: RemoveCommerceReservationRequest,
): string {
  return JSON.stringify(
    RemoveCommerceReservationRequest$outboundSchema.parse(
      removeCommerceReservationRequest,
    ),
  );
}

/** @internal */
export const RemoveCommerceReservationResponse$inboundSchema: z.ZodType<
  RemoveCommerceReservationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

export function removeCommerceReservationResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveCommerceReservationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveCommerceReservationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveCommerceReservationResponse' from JSON`,
  );
}
