/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemoveHrisEmployeeRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * ID of the Employee
   */
  id: string;
};

export type RemoveHrisEmployeeResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type RemoveHrisEmployeeRequest$Outbound = {
  connection_id: string;
  id: string;
};

/** @internal */
export const RemoveHrisEmployeeRequest$outboundSchema: z.ZodType<
  RemoveHrisEmployeeRequest$Outbound,
  z.ZodTypeDef,
  RemoveHrisEmployeeRequest
> = z.object({
  connectionId: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function removeHrisEmployeeRequestToJSON(
  removeHrisEmployeeRequest: RemoveHrisEmployeeRequest,
): string {
  return JSON.stringify(
    RemoveHrisEmployeeRequest$outboundSchema.parse(removeHrisEmployeeRequest),
  );
}

/** @internal */
export const RemoveHrisEmployeeResponse$inboundSchema: z.ZodType<
  RemoveHrisEmployeeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

export function removeHrisEmployeeResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveHrisEmployeeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveHrisEmployeeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveHrisEmployeeResponse' from JSON`,
  );
}
