/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemoveUcRecording2Request = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * ID of the Recording
   */
  id: string;
};

export type RemoveUcRecording2Response = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type RemoveUcRecording2Request$Outbound = {
  connection_id: string;
  id: string;
};

/** @internal */
export const RemoveUcRecording2Request$outboundSchema: z.ZodType<
  RemoveUcRecording2Request$Outbound,
  z.ZodTypeDef,
  RemoveUcRecording2Request
> = z.object({
  connectionId: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function removeUcRecording2RequestToJSON(
  removeUcRecording2Request: RemoveUcRecording2Request,
): string {
  return JSON.stringify(
    RemoveUcRecording2Request$outboundSchema.parse(removeUcRecording2Request),
  );
}

/** @internal */
export const RemoveUcRecording2Response$inboundSchema: z.ZodType<
  RemoveUcRecording2Response,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

export function removeUcRecording2ResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveUcRecording2Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveUcRecording2Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveUcRecording2Response' from JSON`,
  );
}
