/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RemoveAtsCandidateRequest = {
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * ID of the Candidate
   */
  id: string;
};

export type RemoveAtsCandidateResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type RemoveAtsCandidateRequest$Outbound = {
  connection_id: string;
  id: string;
};

/** @internal */
export const RemoveAtsCandidateRequest$outboundSchema: z.ZodType<
  RemoveAtsCandidateRequest$Outbound,
  z.ZodTypeDef,
  RemoveAtsCandidateRequest
> = z.object({
  connectionId: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
  });
});

export function removeAtsCandidateRequestToJSON(
  removeAtsCandidateRequest: RemoveAtsCandidateRequest,
): string {
  return JSON.stringify(
    RemoveAtsCandidateRequest$outboundSchema.parse(removeAtsCandidateRequest),
  );
}

/** @internal */
export const RemoveAtsCandidateResponse$inboundSchema: z.ZodType<
  RemoveAtsCandidateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
  });
});

export function removeAtsCandidateResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveAtsCandidateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveAtsCandidateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveAtsCandidateResponse' from JSON`,
  );
}
