/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const UpdateSigningSignatoryQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  DocumentId: "document_id",
  Name: "name",
  Email: "email",
  Role: "role",
  Status: "status",
  Order: "order",
  SignedAt: "signed_at",
  DeclineReason: "decline_reason",
  Raw: "raw",
} as const;
export type UpdateSigningSignatoryQueryParamFields = ClosedEnum<
  typeof UpdateSigningSignatoryQueryParamFields
>;

export type UpdateSigningSignatoryRequest = {
  signingSignatory: shared.SigningSignatory;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<UpdateSigningSignatoryQueryParamFields> | undefined;
  /**
   * ID of the Signatory
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const UpdateSigningSignatoryQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof UpdateSigningSignatoryQueryParamFields> = z.nativeEnum(
    UpdateSigningSignatoryQueryParamFields,
  );

/** @internal */
export type UpdateSigningSignatoryRequest$Outbound = {
  SigningSignatory: shared.SigningSignatory$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const UpdateSigningSignatoryRequest$outboundSchema: z.ZodType<
  UpdateSigningSignatoryRequest$Outbound,
  z.ZodTypeDef,
  UpdateSigningSignatoryRequest
> = z.object({
  signingSignatory: shared.SigningSignatory$outboundSchema,
  connectionId: z.string(),
  fields: z.array(UpdateSigningSignatoryQueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    signingSignatory: "SigningSignatory",
    connectionId: "connection_id",
  });
});

export function updateSigningSignatoryRequestToJSON(
  updateSigningSignatoryRequest: UpdateSigningSignatoryRequest,
): string {
  return JSON.stringify(
    UpdateSigningSignatoryRequest$outboundSchema.parse(
      updateSigningSignatoryRequest,
    ),
  );
}
