/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const UpdateCommerceInventory2QueryParamFields = {
  Id: "id",
  UpdatedAt: "updated_at",
  ItemId: "item_id",
  ItemVariantId: "item_variant_id",
  ItemOptionId: "item_option_id",
  LocationId: "location_id",
  Available: "available",
  Raw: "raw",
} as const;
export type UpdateCommerceInventory2QueryParamFields = ClosedEnum<
  typeof UpdateCommerceInventory2QueryParamFields
>;

export type UpdateCommerceInventory2Request = {
  commerceInventory: shared.CommerceInventory;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<UpdateCommerceInventory2QueryParamFields> | undefined;
  /**
   * ID of the Inventory
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const UpdateCommerceInventory2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof UpdateCommerceInventory2QueryParamFields> = z
    .nativeEnum(UpdateCommerceInventory2QueryParamFields);

/** @internal */
export type UpdateCommerceInventory2Request$Outbound = {
  CommerceInventory: shared.CommerceInventory$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const UpdateCommerceInventory2Request$outboundSchema: z.ZodType<
  UpdateCommerceInventory2Request$Outbound,
  z.ZodTypeDef,
  UpdateCommerceInventory2Request
> = z.object({
  commerceInventory: shared.CommerceInventory$outboundSchema,
  connectionId: z.string(),
  fields: z.array(UpdateCommerceInventory2QueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    commerceInventory: "CommerceInventory",
    connectionId: "connection_id",
  });
});

export function updateCommerceInventory2RequestToJSON(
  updateCommerceInventory2Request: UpdateCommerceInventory2Request,
): string {
  return JSON.stringify(
    UpdateCommerceInventory2Request$outboundSchema.parse(
      updateCommerceInventory2Request,
    ),
  );
}
