/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const UpdateDatastoreDatabase2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  Description: "description",
  WebUrl: "web_url",
  IsActive: "is_active",
  Password: "password",
  Region: "region",
  Raw: "raw",
} as const;
export type UpdateDatastoreDatabase2QueryParamFields = ClosedEnum<
  typeof UpdateDatastoreDatabase2QueryParamFields
>;

export type UpdateDatastoreDatabase2Request = {
  datastoreDatabase: shared.DatastoreDatabase;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<UpdateDatastoreDatabase2QueryParamFields> | undefined;
  /**
   * ID of the Database
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const UpdateDatastoreDatabase2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof UpdateDatastoreDatabase2QueryParamFields> = z
    .nativeEnum(UpdateDatastoreDatabase2QueryParamFields);

/** @internal */
export type UpdateDatastoreDatabase2Request$Outbound = {
  DatastoreDatabase: shared.DatastoreDatabase$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const UpdateDatastoreDatabase2Request$outboundSchema: z.ZodType<
  UpdateDatastoreDatabase2Request$Outbound,
  z.ZodTypeDef,
  UpdateDatastoreDatabase2Request
> = z.object({
  datastoreDatabase: shared.DatastoreDatabase$outboundSchema,
  connectionId: z.string(),
  fields: z.array(UpdateDatastoreDatabase2QueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    datastoreDatabase: "DatastoreDatabase",
    connectionId: "connection_id",
  });
});

export function updateDatastoreDatabase2RequestToJSON(
  updateDatastoreDatabase2Request: UpdateDatastoreDatabase2Request,
): string {
  return JSON.stringify(
    UpdateDatastoreDatabase2Request$outboundSchema.parse(
      updateDatastoreDatabase2Request,
    ),
  );
}
