/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const UpdateCommerceReview2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  ItemId: "item_id",
  ItemVariantId: "item_variant_id",
  LocationId: "location_id",
  Rating: "rating",
  Title: "title",
  Content: "content",
  AuthorName: "author_name",
  AuthorEmail: "author_email",
  AuthorAvatarUrl: "author_avatar_url",
  AuthorLocation: "author_location",
  VerifiedPurchase: "verified_purchase",
  HelpfulVotes: "helpful_votes",
  UnhelpfulVotes: "unhelpful_votes",
  Media: "media",
  Status: "status",
  IsVerified: "is_verified",
  IsFeatured: "is_featured",
  IsPublic: "is_public",
  Comments: "comments",
  Metadata: "metadata",
  Url: "url",
  Raw: "raw",
} as const;
export type UpdateCommerceReview2QueryParamFields = ClosedEnum<
  typeof UpdateCommerceReview2QueryParamFields
>;

export type UpdateCommerceReview2Request = {
  commerceReview: shared.CommerceReview;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<UpdateCommerceReview2QueryParamFields> | undefined;
  /**
   * ID of the Review
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const UpdateCommerceReview2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof UpdateCommerceReview2QueryParamFields> = z.nativeEnum(
    UpdateCommerceReview2QueryParamFields,
  );

/** @internal */
export type UpdateCommerceReview2Request$Outbound = {
  CommerceReview: shared.CommerceReview$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const UpdateCommerceReview2Request$outboundSchema: z.ZodType<
  UpdateCommerceReview2Request$Outbound,
  z.ZodTypeDef,
  UpdateCommerceReview2Request
> = z.object({
  commerceReview: shared.CommerceReview$outboundSchema,
  connectionId: z.string(),
  fields: z.array(UpdateCommerceReview2QueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    commerceReview: "CommerceReview",
    connectionId: "connection_id",
  });
});

export function updateCommerceReview2RequestToJSON(
  updateCommerceReview2Request: UpdateCommerceReview2Request,
): string {
  return JSON.stringify(
    UpdateCommerceReview2Request$outboundSchema.parse(
      updateCommerceReview2Request,
    ),
  );
}
