/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const UpdateShippingShipmentQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  OrderId: "order_id",
  FromAddress: "from_address",
  ToAddress: "to_address",
  Packages: "packages",
  CarrierId: "carrier_id",
  ServiceCode: "service_code",
  Status: "status",
  RateId: "rate_id",
  LabelId: "label_id",
  TrackingId: "tracking_id",
  ShippedAt: "shipped_at",
  RateAmount: "rate_amount",
  RateCurrency: "rate_currency",
  RateServiceName: "rate_service_name",
  RateEstimatedDays: "rate_estimated_days",
  RateEstimatedDeliveryAt: "rate_estimated_delivery_at",
  IsRateGuaranteed: "is_rate_guaranteed",
  ReturnAddress: "return_address",
  ReturnAuthorizationNumber: "return_authorization_number",
  WarehouseLocationId: "warehouse_location_id",
  WarehouseLocationName: "warehouse_location_name",
  Customs: "customs",
  IsInternational: "is_international",
  Insurance: "insurance",
  SpecialInstructions: "special_instructions",
  IsSignatureRequired: "is_signature_required",
  IsAdultSignatureRequired: "is_adult_signature_required",
  ReferenceNumber: "reference_number",
  IsReturn: "is_return",
  OriginalShipmentId: "original_shipment_id",
  ReturnReason: "return_reason",
  ReturnType: "return_type",
  Raw: "raw",
} as const;
export type UpdateShippingShipmentQueryParamFields = ClosedEnum<
  typeof UpdateShippingShipmentQueryParamFields
>;

export type UpdateShippingShipmentRequest = {
  shippingShipment: shared.ShippingShipment;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<UpdateShippingShipmentQueryParamFields> | undefined;
  /**
   * ID of the Shipment
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const UpdateShippingShipmentQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof UpdateShippingShipmentQueryParamFields> = z.nativeEnum(
    UpdateShippingShipmentQueryParamFields,
  );

/** @internal */
export type UpdateShippingShipmentRequest$Outbound = {
  ShippingShipment: shared.ShippingShipment$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const UpdateShippingShipmentRequest$outboundSchema: z.ZodType<
  UpdateShippingShipmentRequest$Outbound,
  z.ZodTypeDef,
  UpdateShippingShipmentRequest
> = z.object({
  shippingShipment: shared.ShippingShipment$outboundSchema,
  connectionId: z.string(),
  fields: z.array(UpdateShippingShipmentQueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    shippingShipment: "ShippingShipment",
    connectionId: "connection_id",
  });
});

export function updateShippingShipmentRequestToJSON(
  updateShippingShipmentRequest: UpdateShippingShipmentRequest,
): string {
  return JSON.stringify(
    UpdateShippingShipmentRequest$outboundSchema.parse(
      updateShippingShipmentRequest,
    ),
  );
}
