/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const UpdateAnalyticsPropertyQueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  Timezone: "timezone",
  Currency: "currency",
  Industry: "industry",
  ParentId: "parent_id",
  Raw: "raw",
} as const;
export type UpdateAnalyticsPropertyQueryParamFields = ClosedEnum<
  typeof UpdateAnalyticsPropertyQueryParamFields
>;

export type UpdateAnalyticsPropertyRequest = {
  analyticsProperty: shared.AnalyticsProperty;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<UpdateAnalyticsPropertyQueryParamFields> | undefined;
  /**
   * ID of the Property
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const UpdateAnalyticsPropertyQueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof UpdateAnalyticsPropertyQueryParamFields> = z
    .nativeEnum(UpdateAnalyticsPropertyQueryParamFields);

/** @internal */
export type UpdateAnalyticsPropertyRequest$Outbound = {
  AnalyticsProperty: shared.AnalyticsProperty$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const UpdateAnalyticsPropertyRequest$outboundSchema: z.ZodType<
  UpdateAnalyticsPropertyRequest$Outbound,
  z.ZodTypeDef,
  UpdateAnalyticsPropertyRequest
> = z.object({
  analyticsProperty: shared.AnalyticsProperty$outboundSchema,
  connectionId: z.string(),
  fields: z.array(UpdateAnalyticsPropertyQueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    analyticsProperty: "AnalyticsProperty",
    connectionId: "connection_id",
  });
});

export function updateAnalyticsPropertyRequestToJSON(
  updateAnalyticsPropertyRequest: UpdateAnalyticsPropertyRequest,
): string {
  return JSON.stringify(
    UpdateAnalyticsPropertyRequest$outboundSchema.parse(
      updateAnalyticsPropertyRequest,
    ),
  );
}
