/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const UpdateUcComment2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Content: "content",
  UserId: "user_id",
  CallId: "call_id",
  Raw: "raw",
} as const;
export type UpdateUcComment2QueryParamFields = ClosedEnum<
  typeof UpdateUcComment2QueryParamFields
>;

export type UpdateUcComment2Request = {
  ucComment: shared.UcComment;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<UpdateUcComment2QueryParamFields> | undefined;
  /**
   * ID of the Comment
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const UpdateUcComment2QueryParamFields$outboundSchema: z.ZodNativeEnum<
  typeof UpdateUcComment2QueryParamFields
> = z.nativeEnum(UpdateUcComment2QueryParamFields);

/** @internal */
export type UpdateUcComment2Request$Outbound = {
  UcComment: shared.UcComment$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const UpdateUcComment2Request$outboundSchema: z.ZodType<
  UpdateUcComment2Request$Outbound,
  z.ZodTypeDef,
  UpdateUcComment2Request
> = z.object({
  ucComment: shared.UcComment$outboundSchema,
  connectionId: z.string(),
  fields: z.array(UpdateUcComment2QueryParamFields$outboundSchema).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    ucComment: "UcComment",
    connectionId: "connection_id",
  });
});

export function updateUcComment2RequestToJSON(
  updateUcComment2Request: UpdateUcComment2Request,
): string {
  return JSON.stringify(
    UpdateUcComment2Request$outboundSchema.parse(updateUcComment2Request),
  );
}
