/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";

export type UpdateCalendarEventRequest = {
  calendarEvent: shared.CalendarEvent;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  /**
   * ID of the Event
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export type UpdateCalendarEventRequest$Outbound = {
  CalendarEvent: shared.CalendarEvent$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const UpdateCalendarEventRequest$outboundSchema: z.ZodType<
  UpdateCalendarEventRequest$Outbound,
  z.ZodTypeDef,
  UpdateCalendarEventRequest
> = z.object({
  calendarEvent: shared.CalendarEvent$outboundSchema,
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    calendarEvent: "CalendarEvent",
    connectionId: "connection_id",
  });
});

export function updateCalendarEventRequestToJSON(
  updateCalendarEventRequest: UpdateCalendarEventRequest,
): string {
  return JSON.stringify(
    UpdateCalendarEventRequest$outboundSchema.parse(updateCalendarEventRequest),
  );
}
