/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type UpdateTicketingNoteRequest = {
  ticketingNote?: shared.TicketingNote | undefined;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  /**
   * ID of the Note
   */
  id: string;
};

/** @internal */
export const UpdateTicketingNoteRequest$inboundSchema: z.ZodType<
  UpdateTicketingNoteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  TicketingNote: shared.TicketingNote$inboundSchema.optional(),
  connection_id: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "TicketingNote": "ticketingNote",
    "connection_id": "connectionId",
  });
});

/** @internal */
export type UpdateTicketingNoteRequest$Outbound = {
  TicketingNote?: shared.TicketingNote$Outbound | undefined;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
};

/** @internal */
export const UpdateTicketingNoteRequest$outboundSchema: z.ZodType<
  UpdateTicketingNoteRequest$Outbound,
  z.ZodTypeDef,
  UpdateTicketingNoteRequest
> = z.object({
  ticketingNote: shared.TicketingNote$outboundSchema.optional(),
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    ticketingNote: "TicketingNote",
    connectionId: "connection_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTicketingNoteRequest$ {
  /** @deprecated use `UpdateTicketingNoteRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateTicketingNoteRequest$inboundSchema;
  /** @deprecated use `UpdateTicketingNoteRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateTicketingNoteRequest$outboundSchema;
  /** @deprecated use `UpdateTicketingNoteRequest$Outbound` instead. */
  export type Outbound = UpdateTicketingNoteRequest$Outbound;
}

export function updateTicketingNoteRequestToJSON(
  updateTicketingNoteRequest: UpdateTicketingNoteRequest,
): string {
  return JSON.stringify(
    UpdateTicketingNoteRequest$outboundSchema.parse(updateTicketingNoteRequest),
  );
}

export function updateTicketingNoteRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTicketingNoteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTicketingNoteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTicketingNoteRequest' from JSON`,
  );
}
