/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type UpdateCommerceCollectionRequest = {
  /**
   * A collection of items/products/services
   */
  commerceCollection: shared.CommerceCollection;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Comma-delimited fields to return
   */
  fields?: Array<string> | undefined;
  /**
   * ID of the Collection
   */
  id: string;
};

/** @internal */
export const UpdateCommerceCollectionRequest$inboundSchema: z.ZodType<
  UpdateCommerceCollectionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  CommerceCollection: shared.CommerceCollection$inboundSchema,
  connection_id: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "CommerceCollection": "commerceCollection",
    "connection_id": "connectionId",
  });
});

/** @internal */
export type UpdateCommerceCollectionRequest$Outbound = {
  CommerceCollection: shared.CommerceCollection$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
};

/** @internal */
export const UpdateCommerceCollectionRequest$outboundSchema: z.ZodType<
  UpdateCommerceCollectionRequest$Outbound,
  z.ZodTypeDef,
  UpdateCommerceCollectionRequest
> = z.object({
  commerceCollection: shared.CommerceCollection$outboundSchema,
  connectionId: z.string(),
  fields: z.array(z.string()).optional(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    commerceCollection: "CommerceCollection",
    connectionId: "connection_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCommerceCollectionRequest$ {
  /** @deprecated use `UpdateCommerceCollectionRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateCommerceCollectionRequest$inboundSchema;
  /** @deprecated use `UpdateCommerceCollectionRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateCommerceCollectionRequest$outboundSchema;
  /** @deprecated use `UpdateCommerceCollectionRequest$Outbound` instead. */
  export type Outbound = UpdateCommerceCollectionRequest$Outbound;
}

export function updateCommerceCollectionRequestToJSON(
  updateCommerceCollectionRequest: UpdateCommerceCollectionRequest,
): string {
  return JSON.stringify(
    UpdateCommerceCollectionRequest$outboundSchema.parse(
      updateCommerceCollectionRequest,
    ),
  );
}

export function updateCommerceCollectionRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCommerceCollectionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCommerceCollectionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCommerceCollectionRequest' from JSON`,
  );
}
