/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as shared from "../shared/index.js";

export const UpdateAccountingExpense2QueryParamFields = {
  Id: "id",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  UserId: "user_id",
  ContactId: "contact_id",
  AccountId: "account_id",
  Name: "name",
  PaymentMethod: "payment_method",
  PostedAt: "posted_at",
  TotalAmount: "total_amount",
  Currency: "currency",
  TaxAmount: "tax_amount",
  ReimbursedAmount: "reimbursed_amount",
  ReimbursedAt: "reimbursed_at",
  ApprovedAt: "approved_at",
  ApproverUserId: "approver_user_id",
  Lineitems: "lineitems",
  Raw: "raw",
  OrganizationId: "organization_id",
} as const;
export type UpdateAccountingExpense2QueryParamFields = ClosedEnum<
  typeof UpdateAccountingExpense2QueryParamFields
>;

export type UpdateAccountingExpense2Request = {
  accountingExpense: shared.AccountingExpense;
  /**
   * ID of the connection
   */
  connectionId: string;
  /**
   * Fields to return
   */
  fields?: Array<UpdateAccountingExpense2QueryParamFields> | undefined;
  /**
   * ID of the Expense
   */
  id: string;
  /**
   * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
   */
  raw?: string | undefined;
};

/** @internal */
export const UpdateAccountingExpense2QueryParamFields$outboundSchema:
  z.ZodNativeEnum<typeof UpdateAccountingExpense2QueryParamFields> = z
    .nativeEnum(UpdateAccountingExpense2QueryParamFields);

/** @internal */
export type UpdateAccountingExpense2Request$Outbound = {
  AccountingExpense: shared.AccountingExpense$Outbound;
  connection_id: string;
  fields?: Array<string> | undefined;
  id: string;
  raw?: string | undefined;
};

/** @internal */
export const UpdateAccountingExpense2Request$outboundSchema: z.ZodType<
  UpdateAccountingExpense2Request$Outbound,
  z.ZodTypeDef,
  UpdateAccountingExpense2Request
> = z.object({
  accountingExpense: shared.AccountingExpense$outboundSchema,
  connectionId: z.string(),
  fields: z.array(UpdateAccountingExpense2QueryParamFields$outboundSchema)
    .optional(),
  id: z.string(),
  raw: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountingExpense: "AccountingExpense",
    connectionId: "connection_id",
  });
});

export function updateAccountingExpense2RequestToJSON(
  updateAccountingExpense2Request: UpdateAccountingExpense2Request,
): string {
  return JSON.stringify(
    UpdateAccountingExpense2Request$outboundSchema.parse(
      updateAccountingExpense2Request,
    ),
  );
}
