/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingCreateAccountingPaymentterm } from "../funcs/accountingCreateAccountingPaymentterm.js";
import { accountingGetAccountingPaymentterm } from "../funcs/accountingGetAccountingPaymentterm.js";
import { accountingListAccountingPaymentterms } from "../funcs/accountingListAccountingPaymentterms.js";
import { accountingPatchAccountingPaymentterm } from "../funcs/accountingPatchAccountingPaymentterm.js";
import { accountingRemoveAccountingPaymentterm } from "../funcs/accountingRemoveAccountingPaymentterm.js";
import { accountingUpdateAccountingPaymentterm } from "../funcs/accountingUpdateAccountingPaymentterm.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Paymentterm extends ClientSDK {
  /**
   * Create a paymentterm
   */
  async createAccountingPaymentterm(
    request: operations.CreateAccountingPaymenttermRequest,
    options?: RequestOptions,
  ): Promise<shared.AccountingPaymentterm> {
    return unwrapAsync(accountingCreateAccountingPaymentterm(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a paymentterm
   */
  async getAccountingPaymentterm(
    request: operations.GetAccountingPaymenttermRequest,
    options?: RequestOptions,
  ): Promise<shared.AccountingPaymentterm> {
    return unwrapAsync(accountingGetAccountingPaymentterm(
      this,
      request,
      options,
    ));
  }

  /**
   * List all paymentterms
   */
  async listAccountingPaymentterms(
    request: operations.ListAccountingPaymenttermsRequest,
    options?: RequestOptions,
  ): Promise<Array<shared.AccountingPaymentterm>> {
    return unwrapAsync(accountingListAccountingPaymentterms(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a paymentterm
   */
  async patchAccountingPaymentterm(
    request: operations.PatchAccountingPaymenttermRequest,
    options?: RequestOptions,
  ): Promise<shared.AccountingPaymentterm> {
    return unwrapAsync(accountingPatchAccountingPaymentterm(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a paymentterm
   */
  async removeAccountingPaymentterm(
    request: operations.RemoveAccountingPaymenttermRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveAccountingPaymenttermResponse | undefined> {
    return unwrapAsync(accountingRemoveAccountingPaymentterm(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a paymentterm
   */
  async updateAccountingPaymentterm(
    request: operations.UpdateAccountingPaymenttermRequest,
    options?: RequestOptions,
  ): Promise<shared.AccountingPaymentterm> {
    return unwrapAsync(accountingUpdateAccountingPaymentterm(
      this,
      request,
      options,
    ));
  }
}
