/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentGetPaymentPayout2 } from "../funcs/paymentGetPaymentPayout2.js";
import { paymentListPaymentPayouts2 } from "../funcs/paymentListPaymentPayouts2.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Payout extends ClientSDK {
  /**
   * Retrieve a payout
   */
  async getPaymentPayout2(
    request: operations.GetPaymentPayout2Request,
    options?: RequestOptions,
  ): Promise<shared.PaymentPayout> {
    return unwrapAsync(paymentGetPaymentPayout2(
      this,
      request,
      options,
    ));
  }

  /**
   * List all payouts
   */
  async listPaymentPayouts2(
    request: operations.ListPaymentPayouts2Request,
    options?: RequestOptions,
  ): Promise<Array<shared.PaymentPayout>> {
    return unwrapAsync(paymentListPaymentPayouts2(
      this,
      request,
      options,
    ));
  }
}
