/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taskCreateTaskProject2 } from "../funcs/taskCreateTaskProject2.js";
import { taskGetTaskProject2 } from "../funcs/taskGetTaskProject2.js";
import { taskListTaskProjects2 } from "../funcs/taskListTaskProjects2.js";
import { taskPatchTaskProject2 } from "../funcs/taskPatchTaskProject2.js";
import { taskRemoveTaskProject2 } from "../funcs/taskRemoveTaskProject2.js";
import { taskUpdateTaskProject2 } from "../funcs/taskUpdateTaskProject2.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Project extends ClientSDK {
  /**
   * Create a project
   */
  async createTaskProject2(
    request: operations.CreateTaskProject2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskProject> {
    return unwrapAsync(taskCreateTaskProject2(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a project
   */
  async getTaskProject2(
    request: operations.GetTaskProject2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskProject> {
    return unwrapAsync(taskGetTaskProject2(
      this,
      request,
      options,
    ));
  }

  /**
   * List all projects
   */
  async listTaskProjects2(
    request: operations.ListTaskProjects2Request,
    options?: RequestOptions,
  ): Promise<Array<shared.TaskProject>> {
    return unwrapAsync(taskListTaskProjects2(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a project
   */
  async patchTaskProject2(
    request: operations.PatchTaskProject2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskProject> {
    return unwrapAsync(taskPatchTaskProject2(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a project
   */
  async removeTaskProject2(
    request: operations.RemoveTaskProject2Request,
    options?: RequestOptions,
  ): Promise<operations.RemoveTaskProject2Response | undefined> {
    return unwrapAsync(taskRemoveTaskProject2(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a project
   */
  async updateTaskProject2(
    request: operations.UpdateTaskProject2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskProject> {
    return unwrapAsync(taskUpdateTaskProject2(
      this,
      request,
      options,
    ));
  }
}
