/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reportGetAccountingReport } from "../funcs/reportGetAccountingReport.js";
import { reportListAccountingReports } from "../funcs/reportListAccountingReports.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Report extends ClientSDK {
  /**
   * Retrieve a report
   */
  async getAccountingReport(
    request: operations.GetAccountingReportRequest,
    options?: RequestOptions,
  ): Promise<shared.AccountingReport> {
    return unwrapAsync(reportGetAccountingReport(
      this,
      request,
      options,
    ));
  }

  /**
   * List all reports
   */
  async listAccountingReports(
    request: operations.ListAccountingReportsRequest,
    options?: RequestOptions,
  ): Promise<Array<shared.AccountingReport>> {
    return unwrapAsync(reportListAccountingReports(
      this,
      request,
      options,
    ));
  }
}
