/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { commentCreateTaskComment2 } from "../funcs/commentCreateTaskComment2.js";
import { commentGetTaskComment2 } from "../funcs/commentGetTaskComment2.js";
import { commentListTaskComments2 } from "../funcs/commentListTaskComments2.js";
import { commentPatchTaskComment2 } from "../funcs/commentPatchTaskComment2.js";
import { commentRemoveTaskComment2 } from "../funcs/commentRemoveTaskComment2.js";
import { commentUpdateTaskComment2 } from "../funcs/commentUpdateTaskComment2.js";
import { taskCreateTaskProject2 } from "../funcs/taskCreateTaskProject2.js";
import { taskCreateTaskTask2 } from "../funcs/taskCreateTaskTask2.js";
import { taskGetTaskChange2 } from "../funcs/taskGetTaskChange2.js";
import { taskGetTaskProject2 } from "../funcs/taskGetTaskProject2.js";
import { taskGetTaskTask2 } from "../funcs/taskGetTaskTask2.js";
import { taskListTaskChanges2 } from "../funcs/taskListTaskChanges2.js";
import { taskListTaskProjects2 } from "../funcs/taskListTaskProjects2.js";
import { taskListTaskTasks2 } from "../funcs/taskListTaskTasks2.js";
import { taskPatchTaskProject2 } from "../funcs/taskPatchTaskProject2.js";
import { taskPatchTaskTask2 } from "../funcs/taskPatchTaskTask2.js";
import { taskRemoveTaskProject2 } from "../funcs/taskRemoveTaskProject2.js";
import { taskRemoveTaskTask2 } from "../funcs/taskRemoveTaskTask2.js";
import { taskUpdateTaskProject2 } from "../funcs/taskUpdateTaskProject2.js";
import { taskUpdateTaskTask2 } from "../funcs/taskUpdateTaskTask2.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Task extends ClientSDK {
  /**
   * Create a comment
   */
  async createTaskComment2(
    request: operations.CreateTaskComment2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskComment> {
    return unwrapAsync(commentCreateTaskComment2(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a project
   */
  async createTaskProject2(
    request: operations.CreateTaskProject2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskProject> {
    return unwrapAsync(taskCreateTaskProject2(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a task
   */
  async createTaskTask2(
    request: operations.CreateTaskTask2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskTask> {
    return unwrapAsync(taskCreateTaskTask2(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a change
   */
  async getTaskChange2(
    request: operations.GetTaskChange2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskChange> {
    return unwrapAsync(taskGetTaskChange2(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a comment
   */
  async getTaskComment2(
    request: operations.GetTaskComment2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskComment> {
    return unwrapAsync(commentGetTaskComment2(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a project
   */
  async getTaskProject2(
    request: operations.GetTaskProject2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskProject> {
    return unwrapAsync(taskGetTaskProject2(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a task
   */
  async getTaskTask2(
    request: operations.GetTaskTask2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskTask> {
    return unwrapAsync(taskGetTaskTask2(
      this,
      request,
      options,
    ));
  }

  /**
   * List all changes
   */
  async listTaskChanges2(
    request: operations.ListTaskChanges2Request,
    options?: RequestOptions,
  ): Promise<Array<shared.TaskChange>> {
    return unwrapAsync(taskListTaskChanges2(
      this,
      request,
      options,
    ));
  }

  /**
   * List all comments
   */
  async listTaskComments2(
    request: operations.ListTaskComments2Request,
    options?: RequestOptions,
  ): Promise<Array<shared.TaskComment>> {
    return unwrapAsync(commentListTaskComments2(
      this,
      request,
      options,
    ));
  }

  /**
   * List all projects
   */
  async listTaskProjects2(
    request: operations.ListTaskProjects2Request,
    options?: RequestOptions,
  ): Promise<Array<shared.TaskProject>> {
    return unwrapAsync(taskListTaskProjects2(
      this,
      request,
      options,
    ));
  }

  /**
   * List all tasks
   */
  async listTaskTasks2(
    request: operations.ListTaskTasks2Request,
    options?: RequestOptions,
  ): Promise<Array<shared.TaskTask>> {
    return unwrapAsync(taskListTaskTasks2(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a comment
   */
  async patchTaskComment2(
    request: operations.PatchTaskComment2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskComment> {
    return unwrapAsync(commentPatchTaskComment2(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a project
   */
  async patchTaskProject2(
    request: operations.PatchTaskProject2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskProject> {
    return unwrapAsync(taskPatchTaskProject2(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a task
   */
  async patchTaskTask2(
    request: operations.PatchTaskTask2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskTask> {
    return unwrapAsync(taskPatchTaskTask2(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a comment
   */
  async removeTaskComment2(
    request: operations.RemoveTaskComment2Request,
    options?: RequestOptions,
  ): Promise<operations.RemoveTaskComment2Response | undefined> {
    return unwrapAsync(commentRemoveTaskComment2(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a project
   */
  async removeTaskProject2(
    request: operations.RemoveTaskProject2Request,
    options?: RequestOptions,
  ): Promise<operations.RemoveTaskProject2Response | undefined> {
    return unwrapAsync(taskRemoveTaskProject2(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a task
   */
  async removeTaskTask2(
    request: operations.RemoveTaskTask2Request,
    options?: RequestOptions,
  ): Promise<operations.RemoveTaskTask2Response | undefined> {
    return unwrapAsync(taskRemoveTaskTask2(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a comment
   */
  async updateTaskComment2(
    request: operations.UpdateTaskComment2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskComment> {
    return unwrapAsync(commentUpdateTaskComment2(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a project
   */
  async updateTaskProject2(
    request: operations.UpdateTaskProject2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskProject> {
    return unwrapAsync(taskUpdateTaskProject2(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a task
   */
  async updateTaskTask2(
    request: operations.UpdateTaskTask2Request,
    options?: RequestOptions,
  ): Promise<shared.TaskTask> {
    return unwrapAsync(taskUpdateTaskTask2(
      this,
      request,
      options,
    ));
  }
}
