/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { signingGetSigningTemplate } from "../funcs/signingGetSigningTemplate.js";
import { signingListSigningTemplates } from "../funcs/signingListSigningTemplates.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Template extends ClientSDK {
  /**
   * Retrieve a template
   */
  async getSigningTemplate(
    request: operations.GetSigningTemplateRequest,
    options?: RequestOptions,
  ): Promise<shared.SigningTemplate> {
    return unwrapAsync(signingGetSigningTemplate(
      this,
      request,
      options,
    ));
  }

  /**
   * List all templates
   */
  async listSigningTemplates(
    request: operations.ListSigningTemplatesRequest,
    options?: RequestOptions,
  ): Promise<Array<shared.SigningTemplate>> {
    return unwrapAsync(signingListSigningTemplates(
      this,
      request,
      options,
    ));
  }
}
