/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingCreateAccountingVendorcredit } from "../funcs/accountingCreateAccountingVendorcredit.js";
import { accountingGetAccountingVendorcredit } from "../funcs/accountingGetAccountingVendorcredit.js";
import { accountingListAccountingVendorcredits } from "../funcs/accountingListAccountingVendorcredits.js";
import { accountingPatchAccountingVendorcredit } from "../funcs/accountingPatchAccountingVendorcredit.js";
import { accountingRemoveAccountingVendorcredit } from "../funcs/accountingRemoveAccountingVendorcredit.js";
import { accountingUpdateAccountingVendorcredit } from "../funcs/accountingUpdateAccountingVendorcredit.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Vendorcredit extends ClientSDK {
  /**
   * Create a vendorcredit
   */
  async createAccountingVendorcredit(
    request: operations.CreateAccountingVendorcreditRequest,
    options?: RequestOptions,
  ): Promise<shared.AccountingVendorcredit> {
    return unwrapAsync(accountingCreateAccountingVendorcredit(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a vendorcredit
   */
  async getAccountingVendorcredit(
    request: operations.GetAccountingVendorcreditRequest,
    options?: RequestOptions,
  ): Promise<shared.AccountingVendorcredit> {
    return unwrapAsync(accountingGetAccountingVendorcredit(
      this,
      request,
      options,
    ));
  }

  /**
   * List all vendorcredits
   */
  async listAccountingVendorcredits(
    request: operations.ListAccountingVendorcreditsRequest,
    options?: RequestOptions,
  ): Promise<Array<shared.AccountingVendorcredit>> {
    return unwrapAsync(accountingListAccountingVendorcredits(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a vendorcredit
   */
  async patchAccountingVendorcredit(
    request: operations.PatchAccountingVendorcreditRequest,
    options?: RequestOptions,
  ): Promise<shared.AccountingVendorcredit> {
    return unwrapAsync(accountingPatchAccountingVendorcredit(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove a vendorcredit
   */
  async removeAccountingVendorcredit(
    request: operations.RemoveAccountingVendorcreditRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveAccountingVendorcreditResponse | undefined> {
    return unwrapAsync(accountingRemoveAccountingVendorcredit(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a vendorcredit
   */
  async updateAccountingVendorcredit(
    request: operations.UpdateAccountingVendorcreditRequest,
    options?: RequestOptions,
  ): Promise<shared.AccountingVendorcredit> {
    return unwrapAsync(accountingUpdateAccountingVendorcredit(
      this,
      request,
      options,
    ));
  }
}
